// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateAdminErrors = `-- name: AggregateAdminErrors :many
SELECT
    COALESCE(NULLIF(error_code, ''), 'unknown')::text AS code,
    COUNT(*)::bigint AS count
FROM generations
WHERE completed_at >= $1
  AND completed_at < $2
  AND status IN ('failed', 'rejected')
GROUP BY COALESCE(NULLIF(error_code, ''), 'unknown')
ORDER BY count DESC, code
`

type AggregateAdminErrorsParams struct {
	PeriodStart pgtype.Timestamptz `db:"period_start"`
	PeriodEnd   pgtype.Timestamptz `db:"period_end"`
}

type AggregateAdminErrorsRow struct {
	Code  string `db:"code"`
	Count int64  `db:"count"`
}

func (q *Queries) AggregateAdminErrors(ctx context.Context, arg AggregateAdminErrorsParams) ([]AggregateAdminErrorsRow, error) {
	rows, err := q.db.Query(ctx, aggregateAdminErrors, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateAdminErrorsRow{}
	for rows.Next() {
		var i AggregateAdminErrorsRow
		if err := rows.Scan(&i.Code, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggregateAdminUsage = `-- name: AggregateAdminUsage :one
SELECT
    COUNT(*)::bigint AS generations,
    COUNT(*) FILTER (
        WHERE generations.status IN ('failed', 'rejected')
    )::bigint AS failed_generations,
    COALESCE(SUM(usage_ledger.input_tokens), 0)::bigint AS input_tokens,
    COALESCE(SUM(usage_ledger.output_tokens), 0)::bigint AS output_tokens,
    COALESCE(SUM(usage_ledger.estimated_cost_microunits), 0)::bigint AS estimated_cost_microunits,
    COALESCE(
        AVG(EXTRACT(EPOCH FROM (generations.completed_at - generations.accepted_at)) * 1000)
            FILTER (WHERE generations.completed_at IS NOT NULL),
        0
    )::double precision AS average_latency_ms,
    COALESCE(
        percentile_cont(0.95) WITHIN GROUP (
            ORDER BY EXTRACT(EPOCH FROM (generations.completed_at - generations.accepted_at)) * 1000
        ) FILTER (WHERE generations.completed_at IS NOT NULL),
        0
    )::double precision AS p95_latency_ms
FROM usage_ledger
JOIN generations ON generations.id = usage_ledger.generation_id
WHERE usage_ledger.occurred_at >= $1
  AND usage_ledger.occurred_at < $2
`

type AggregateAdminUsageParams struct {
	PeriodStart pgtype.Timestamptz `db:"period_start"`
	PeriodEnd   pgtype.Timestamptz `db:"period_end"`
}

type AggregateAdminUsageRow struct {
	Generations             int64   `db:"generations"`
	FailedGenerations       int64   `db:"failed_generations"`
	InputTokens             int64   `db:"input_tokens"`
	OutputTokens            int64   `db:"output_tokens"`
	EstimatedCostMicrounits int64   `db:"estimated_cost_microunits"`
	AverageLatencyMs        float64 `db:"average_latency_ms"`
	P95LatencyMs            float64 `db:"p95_latency_ms"`
}

func (q *Queries) AggregateAdminUsage(ctx context.Context, arg AggregateAdminUsageParams) (AggregateAdminUsageRow, error) {
	row := q.db.QueryRow(ctx, aggregateAdminUsage, arg.PeriodStart, arg.PeriodEnd)
	var i AggregateAdminUsageRow
	err := row.Scan(
		&i.Generations,
		&i.FailedGenerations,
		&i.InputTokens,
		&i.OutputTokens,
		&i.EstimatedCostMicrounits,
		&i.AverageLatencyMs,
		&i.P95LatencyMs,
	)
	return i, err
}

const clearOtherModelDefault = `-- name: ClearOtherModelDefault :many
UPDATE models
SET default_for = array_remove(default_for, $1::text),
    version = version + 1,
    updated_at = $2
WHERE id <> $3
  AND $1::text = ANY(default_for)
RETURNING id, slug, name, description, context_window, max_output_tokens, capabilities, enabled, available, supported, audience, default_for, sort_order, version, created_at, updated_at
`

type ClearOtherModelDefaultParams struct {
	ActorType string             `db:"actor_type"`
	NowAt     pgtype.Timestamptz `db:"now_at"`
	ModelID   uuid.UUID          `db:"model_id"`
}

func (q *Queries) ClearOtherModelDefault(ctx context.Context, arg ClearOtherModelDefaultParams) ([]Model, error) {
	rows, err := q.db.Query(ctx, clearOtherModelDefault, arg.ActorType, arg.NowAt, arg.ModelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Model{}
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.Capabilities,
			&i.Enabled,
			&i.Available,
			&i.Supported,
			&i.Audience,
			&i.DefaultFor,
			&i.SortOrder,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAdministrators = `-- name: CountAdministrators :one
SELECT COUNT(*)::bigint FROM users
WHERE role = 'admin' AND status = 'active'
`

func (q *Queries) CountAdministrators(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdministrators)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSelectableDefaults = `-- name: CountSelectableDefaults :one
SELECT COUNT(*)::bigint
FROM models
WHERE enabled
  AND available
  AND supported
  AND $1::text = ANY(default_for)
`

func (q *Queries) CountSelectableDefaults(ctx context.Context, actorType string) (int64, error) {
	row := q.db.QueryRow(ctx, countSelectableDefaults, actorType)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getAdminModel = `-- name: GetAdminModel :one
SELECT id, slug, name, description, context_window, max_output_tokens, capabilities, enabled, available, supported, audience, default_for, sort_order, version, created_at, updated_at FROM models WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAdminModel(ctx context.Context, id uuid.UUID) (Model, error) {
	row := q.db.QueryRow(ctx, getAdminModel, id)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.Capabilities,
		&i.Enabled,
		&i.Available,
		&i.Supported,
		&i.Audience,
		&i.DefaultFor,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminUser = `-- name: GetAdminUser :one
SELECT id, email, display_name, avatar_url, locale, role, plan, status, token_version, created_at, updated_at, version FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAdminUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getAdminUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Locale,
		&i.Role,
		&i.Plan,
		&i.Status,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getRuntimeSetting = `-- name: GetRuntimeSetting :one
SELECT key, value_kind, value, version, updated_by_user_id, updated_at FROM runtime_settings WHERE key = $1
`

func (q *Queries) GetRuntimeSetting(ctx context.Context, key string) (RuntimeSetting, error) {
	row := q.db.QueryRow(ctx, getRuntimeSetting, key)
	var i RuntimeSetting
	err := row.Scan(
		&i.Key,
		&i.ValueKind,
		&i.Value,
		&i.Version,
		&i.UpdatedByUserID,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminAuditEvents = `-- name: ListAdminAuditEvents :many
SELECT id, actor_user_id, action, target_type, target_id, before_value, after_value, request_id, occurred_at FROM admin_audit_log
WHERE (
    $1::timestamptz IS NULL
    OR (occurred_at, id) < (
        $1::timestamptz,
        $2::uuid
    )
)
ORDER BY occurred_at DESC, id DESC
LIMIT $3
`

type ListAdminAuditEventsParams struct {
	BeforeOccurredAt pgtype.Timestamptz `db:"before_occurred_at"`
	BeforeID         *uuid.UUID         `db:"before_id"`
	PageSize         int32              `db:"page_size"`
}

func (q *Queries) ListAdminAuditEvents(ctx context.Context, arg ListAdminAuditEventsParams) ([]AdminAuditLog, error) {
	rows, err := q.db.Query(ctx, listAdminAuditEvents, arg.BeforeOccurredAt, arg.BeforeID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminAuditLog{}
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.BeforeValue,
			&i.AfterValue,
			&i.RequestID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminModels = `-- name: ListAdminModels :many
SELECT id, slug, name, description, context_window, max_output_tokens, capabilities, enabled, available, supported, audience, default_for, sort_order, version, created_at, updated_at FROM models ORDER BY sort_order, name, id
`

func (q *Queries) ListAdminModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.Query(ctx, listAdminModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Model{}
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.Capabilities,
			&i.Enabled,
			&i.Available,
			&i.Supported,
			&i.Audience,
			&i.DefaultFor,
			&i.SortOrder,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT id, email, display_name, avatar_url, locale, role, plan, status, token_version, created_at, updated_at, version FROM users
WHERE (
    $1::text IS NULL
    OR email ILIKE '%' || $1::text || '%'
    OR display_name ILIKE '%' || $1::text || '%'
)
AND (
    $2::timestamptz IS NULL
    OR (created_at, id) < (
        $2::timestamptz,
        $3::uuid
    )
)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAdminUsersParams struct {
	Query          *string            `db:"query"`
	AfterCreatedAt pgtype.Timestamptz `db:"after_created_at"`
	AfterID        *uuid.UUID         `db:"after_id"`
	PageSize       int32              `db:"page_size"`
}

func (q *Queries) ListAdminUsers(ctx context.Context, arg ListAdminUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listAdminUsers,
		arg.Query,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Locale,
			&i.Role,
			&i.Plan,
			&i.Status,
			&i.TokenVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeSettings = `-- name: ListRuntimeSettings :many
SELECT key, value_kind, value, version, updated_by_user_id, updated_at FROM runtime_settings ORDER BY key
`

func (q *Queries) ListRuntimeSettings(ctx context.Context) ([]RuntimeSetting, error) {
	rows, err := q.db.Query(ctx, listRuntimeSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuntimeSetting{}
	for rows.Next() {
		var i RuntimeSetting
		if err := rows.Scan(
			&i.Key,
			&i.ValueKind,
			&i.Value,
			&i.Version,
			&i.UpdatedByUserID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAdministratorRoleChanges = `-- name: LockAdministratorRoleChanges :exec
SELECT pg_advisory_xact_lock(hashtextextended('glazz.admin-role-changes', 0))
`

func (q *Queries) LockAdministratorRoleChanges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockAdministratorRoleChanges)
	return err
}

const updateAdminModel = `-- name: UpdateAdminModel :one
UPDATE models
SET enabled = COALESCE($1::boolean, enabled),
    audience = COALESCE($2::text[], audience),
    default_for = COALESCE($3::text[], default_for),
    sort_order = COALESCE($4::integer, sort_order),
    version = version + 1,
    updated_at = $5
WHERE id = $6
  AND version = $7
RETURNING id, slug, name, description, context_window, max_output_tokens, capabilities, enabled, available, supported, audience, default_for, sort_order, version, created_at, updated_at
`

type UpdateAdminModelParams struct {
	Enabled         *bool              `db:"enabled"`
	Audience        []string           `db:"audience"`
	DefaultFor      []string           `db:"default_for"`
	SortOrder       *int32             `db:"sort_order"`
	NowAt           pgtype.Timestamptz `db:"now_at"`
	ID              uuid.UUID          `db:"id"`
	ExpectedVersion int32              `db:"expected_version"`
}

func (q *Queries) UpdateAdminModel(ctx context.Context, arg UpdateAdminModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, updateAdminModel,
		arg.Enabled,
		arg.Audience,
		arg.DefaultFor,
		arg.SortOrder,
		arg.NowAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.Capabilities,
		&i.Enabled,
		&i.Available,
		&i.Supported,
		&i.Audience,
		&i.DefaultFor,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRuntimeSetting = `-- name: UpdateRuntimeSetting :one
UPDATE runtime_settings
SET value = $1,
    version = version + 1,
    updated_by_user_id = $2,
    updated_at = $3
WHERE key = $4
  AND version = $5
RETURNING key, value_kind, value, version, updated_by_user_id, updated_at
`

type UpdateRuntimeSettingParams struct {
	Value           []byte             `db:"value"`
	UpdatedByUserID *uuid.UUID         `db:"updated_by_user_id"`
	NowAt           pgtype.Timestamptz `db:"now_at"`
	Key             string             `db:"key"`
	ExpectedVersion int32              `db:"expected_version"`
}

func (q *Queries) UpdateRuntimeSetting(ctx context.Context, arg UpdateRuntimeSettingParams) (RuntimeSetting, error) {
	row := q.db.QueryRow(ctx, updateRuntimeSetting,
		arg.Value,
		arg.UpdatedByUserID,
		arg.NowAt,
		arg.Key,
		arg.ExpectedVersion,
	)
	var i RuntimeSetting
	err := row.Scan(
		&i.Key,
		&i.ValueKind,
		&i.Value,
		&i.Version,
		&i.UpdatedByUserID,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $1,
    version = version + 1,
    updated_at = $2
WHERE id = $3
  AND version = $4
RETURNING id, email, display_name, avatar_url, locale, role, plan, status, token_version, created_at, updated_at, version
`

type UpdateUserRoleParams struct {
	Role            string             `db:"role"`
	NowAt           pgtype.Timestamptz `db:"now_at"`
	ID              uuid.UUID          `db:"id"`
	ExpectedVersion int32              `db:"expected_version"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole,
		arg.Role,
		arg.NowAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Locale,
		&i.Role,
		&i.Plan,
		&i.Status,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
