// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendAssistantMessage = `-- name: AppendAssistantMessage :one
UPDATE messages
SET content = content || $1,
    status = 'pending',
    updated_at = $2
WHERE id = $3
  AND role = 'assistant'
  AND status = 'pending'
RETURNING id, conversation_id, role, content, status, sequence, created_at, updated_at
`

type AppendAssistantMessageParams struct {
	Delta string             `db:"delta"`
	NowAt pgtype.Timestamptz `db:"now_at"`
	ID    uuid.UUID          `db:"id"`
}

func (q *Queries) AppendAssistantMessage(ctx context.Context, arg AppendAssistantMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, appendAssistantMessage, arg.Delta, arg.NowAt, arg.ID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.Status,
		&i.Sequence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const checkpointGeneration = `-- name: CheckpointGeneration :execrows
UPDATE generations
SET stream_offset = $1,
    output_tokens = $2,
    updated_at = $3
WHERE id = $4
  AND status = 'streaming'
  AND stream_offset <= $1
`

type CheckpointGenerationParams struct {
	StreamOffset int32              `db:"stream_offset"`
	OutputTokens int32              `db:"output_tokens"`
	NowAt        pgtype.Timestamptz `db:"now_at"`
	ID           uuid.UUID          `db:"id"`
}

func (q *Queries) CheckpointGeneration(ctx context.Context, arg CheckpointGenerationParams) (int64, error) {
	result, err := q.db.Exec(ctx, checkpointGeneration,
		arg.StreamOffset,
		arg.OutputTokens,
		arg.NowAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActorActiveGenerations = `-- name: CountActorActiveGenerations :one
SELECT COUNT(*)::bigint
FROM generations g
JOIN conversations c ON c.id = g.conversation_id
WHERE g.status IN ('accepted', 'streaming')
  AND (
      ($1::text = 'user' AND c.user_id = $2)
      OR
      ($1::text = 'guest' AND c.guest_session_id = $2)
  )
`

type CountActorActiveGenerationsParams struct {
	ActorType string     `db:"actor_type"`
	ActorID   *uuid.UUID `db:"actor_id"`
}

func (q *Queries) CountActorActiveGenerations(ctx context.Context, arg CountActorActiveGenerationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActorActiveGenerations, arg.ActorType, arg.ActorID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createConversationSummary = `-- name: CreateConversationSummary :one
INSERT INTO conversation_summaries (
    id, conversation_id, model_id, content, from_sequence, through_sequence,
    version, input_tokens, created_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9
)
ON CONFLICT (conversation_id, version) DO UPDATE
SET content = conversation_summaries.content
RETURNING id, conversation_id, model_id, content, from_sequence, through_sequence, version, input_tokens, created_at
`

type CreateConversationSummaryParams struct {
	ID              uuid.UUID          `db:"id"`
	ConversationID  uuid.UUID          `db:"conversation_id"`
	ModelID         uuid.UUID          `db:"model_id"`
	Content         string             `db:"content"`
	FromSequence    int32              `db:"from_sequence"`
	ThroughSequence int32              `db:"through_sequence"`
	Version         int32              `db:"version"`
	InputTokens     int32              `db:"input_tokens"`
	NowAt           pgtype.Timestamptz `db:"now_at"`
}

func (q *Queries) CreateConversationSummary(ctx context.Context, arg CreateConversationSummaryParams) (ConversationSummary, error) {
	row := q.db.QueryRow(ctx, createConversationSummary,
		arg.ID,
		arg.ConversationID,
		arg.ModelID,
		arg.Content,
		arg.FromSequence,
		arg.ThroughSequence,
		arg.Version,
		arg.InputTokens,
		arg.NowAt,
	)
	var i ConversationSummary
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ModelID,
		&i.Content,
		&i.FromSequence,
		&i.ThroughSequence,
		&i.Version,
		&i.InputTokens,
		&i.CreatedAt,
	)
	return i, err
}

const createGeneration = `-- name: CreateGeneration :one
INSERT INTO generations (
    id, conversation_id, user_message_id, assistant_message_id,
    parent_generation_id, model_id, provider_id, quota_reservation_id,
    idempotency_key, status, accepted_at, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8,
    $9, 'accepted', $10, $10
)
ON CONFLICT (conversation_id, idempotency_key) DO UPDATE
SET idempotency_key = EXCLUDED.idempotency_key
WHERE false
RETURNING id, conversation_id, user_message_id, assistant_message_id, parent_generation_id, model_id, provider_id, quota_reservation_id, idempotency_key, status, retryable, finish_reason, error_code, input_tokens, output_tokens, cached_tokens, stream_offset, provider_request_id, accepted_at, started_at, completed_at, updated_at
`

type CreateGenerationParams struct {
	ID                 uuid.UUID          `db:"id"`
	ConversationID     uuid.UUID          `db:"conversation_id"`
	UserMessageID      uuid.UUID          `db:"user_message_id"`
	AssistantMessageID uuid.UUID          `db:"assistant_message_id"`
	ParentGenerationID *uuid.UUID         `db:"parent_generation_id"`
	ModelID            uuid.UUID          `db:"model_id"`
	ProviderID         uuid.UUID          `db:"provider_id"`
	QuotaReservationID *uuid.UUID         `db:"quota_reservation_id"`
	IdempotencyKey     string             `db:"idempotency_key"`
	NowAt              pgtype.Timestamptz `db:"now_at"`
}

func (q *Queries) CreateGeneration(ctx context.Context, arg CreateGenerationParams) (Generation, error) {
	row := q.db.QueryRow(ctx, createGeneration,
		arg.ID,
		arg.ConversationID,
		arg.UserMessageID,
		arg.AssistantMessageID,
		arg.ParentGenerationID,
		arg.ModelID,
		arg.ProviderID,
		arg.QuotaReservationID,
		arg.IdempotencyKey,
		arg.NowAt,
	)
	var i Generation
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.ParentGenerationID,
		&i.ModelID,
		&i.ProviderID,
		&i.QuotaReservationID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Retryable,
		&i.FinishReason,
		&i.ErrorCode,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
		&i.StreamOffset,
		&i.ProviderRequestID,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    id, conversation_id, role, content, status, sequence, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $7
)
RETURNING id, conversation_id, role, content, status, sequence, created_at, updated_at
`

type CreateMessageParams struct {
	ID             uuid.UUID          `db:"id"`
	ConversationID uuid.UUID          `db:"conversation_id"`
	Role           string             `db:"role"`
	Content        string             `db:"content"`
	Status         string             `db:"status"`
	Sequence       int32              `db:"sequence"`
	NowAt          pgtype.Timestamptz `db:"now_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.Status,
		arg.Sequence,
		arg.NowAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.Status,
		&i.Sequence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUsageLedgerEntry = `-- name: CreateUsageLedgerEntry :exec
INSERT INTO usage_ledger (
    id, generation_id, actor_type, actor_id, provider_id, model_id,
    input_tokens, output_tokens, cached_tokens, estimated_cost_microunits, occurred_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9,
    $10, $11
)
ON CONFLICT (generation_id) DO NOTHING
`

type CreateUsageLedgerEntryParams struct {
	ID                      uuid.UUID          `db:"id"`
	GenerationID            uuid.UUID          `db:"generation_id"`
	ActorType               string             `db:"actor_type"`
	ActorID                 uuid.UUID          `db:"actor_id"`
	ProviderID              uuid.UUID          `db:"provider_id"`
	ModelID                 uuid.UUID          `db:"model_id"`
	InputTokens             int32              `db:"input_tokens"`
	OutputTokens            int32              `db:"output_tokens"`
	CachedTokens            int32              `db:"cached_tokens"`
	EstimatedCostMicrounits int64              `db:"estimated_cost_microunits"`
	NowAt                   pgtype.Timestamptz `db:"now_at"`
}

func (q *Queries) CreateUsageLedgerEntry(ctx context.Context, arg CreateUsageLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, createUsageLedgerEntry,
		arg.ID,
		arg.GenerationID,
		arg.ActorType,
		arg.ActorID,
		arg.ProviderID,
		arg.ModelID,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedTokens,
		arg.EstimatedCostMicrounits,
		arg.NowAt,
	)
	return err
}

const finalizeGeneration = `-- name: FinalizeGeneration :one
UPDATE generations
SET status = $1,
    retryable = $2,
    finish_reason = $3,
    error_code = $4,
    input_tokens = $5,
    output_tokens = $6,
    cached_tokens = $7,
    stream_offset = $8,
    provider_request_id = $9,
    completed_at = $10,
    updated_at = $10
WHERE id = $11
  AND status IN ('accepted', 'streaming')
RETURNING id, conversation_id, user_message_id, assistant_message_id, parent_generation_id, model_id, provider_id, quota_reservation_id, idempotency_key, status, retryable, finish_reason, error_code, input_tokens, output_tokens, cached_tokens, stream_offset, provider_request_id, accepted_at, started_at, completed_at, updated_at
`

type FinalizeGenerationParams struct {
	Status            string             `db:"status"`
	Retryable         bool               `db:"retryable"`
	FinishReason      *string            `db:"finish_reason"`
	ErrorCode         *string            `db:"error_code"`
	InputTokens       int32              `db:"input_tokens"`
	OutputTokens      int32              `db:"output_tokens"`
	CachedTokens      int32              `db:"cached_tokens"`
	StreamOffset      int32              `db:"stream_offset"`
	ProviderRequestID *string            `db:"provider_request_id"`
	NowAt             pgtype.Timestamptz `db:"now_at"`
	ID                uuid.UUID          `db:"id"`
}

func (q *Queries) FinalizeGeneration(ctx context.Context, arg FinalizeGenerationParams) (Generation, error) {
	row := q.db.QueryRow(ctx, finalizeGeneration,
		arg.Status,
		arg.Retryable,
		arg.FinishReason,
		arg.ErrorCode,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedTokens,
		arg.StreamOffset,
		arg.ProviderRequestID,
		arg.NowAt,
		arg.ID,
	)
	var i Generation
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.ParentGenerationID,
		&i.ModelID,
		&i.ProviderID,
		&i.QuotaReservationID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Retryable,
		&i.FinishReason,
		&i.ErrorCode,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
		&i.StreamOffset,
		&i.ProviderRequestID,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finalizeMessage = `-- name: FinalizeMessage :execrows
UPDATE messages
SET status = $1,
    updated_at = $2
WHERE id = $3
  AND status = 'pending'
`

type FinalizeMessageParams struct {
	Status string             `db:"status"`
	NowAt  pgtype.Timestamptz `db:"now_at"`
	ID     uuid.UUID          `db:"id"`
}

func (q *Queries) FinalizeMessage(ctx context.Context, arg FinalizeMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, finalizeMessage, arg.Status, arg.NowAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActorUsage = `-- name: GetActorUsage :one
SELECT
    COALESCE(SUM(input_tokens), 0)::bigint AS input_tokens,
    COALESCE(SUM(output_tokens), 0)::bigint AS output_tokens,
    COUNT(*)::bigint AS generations
FROM usage_ledger
WHERE actor_type = $1
  AND actor_id = $2
  AND occurred_at >= $3
`

type GetActorUsageParams struct {
	ActorType string             `db:"actor_type"`
	ActorID   uuid.UUID          `db:"actor_id"`
	FromAt    pgtype.Timestamptz `db:"from_at"`
}

type GetActorUsageRow struct {
	InputTokens  int64 `db:"input_tokens"`
	OutputTokens int64 `db:"output_tokens"`
	Generations  int64 `db:"generations"`
}

func (q *Queries) GetActorUsage(ctx context.Context, arg GetActorUsageParams) (GetActorUsageRow, error) {
	row := q.db.QueryRow(ctx, getActorUsage, arg.ActorType, arg.ActorID, arg.FromAt)
	var i GetActorUsageRow
	err := row.Scan(&i.InputTokens, &i.OutputTokens, &i.Generations)
	return i, err
}

const getGeneration = `-- name: GetGeneration :one
SELECT id, conversation_id, user_message_id, assistant_message_id, parent_generation_id, model_id, provider_id, quota_reservation_id, idempotency_key, status, retryable, finish_reason, error_code, input_tokens, output_tokens, cached_tokens, stream_offset, provider_request_id, accepted_at, started_at, completed_at, updated_at FROM generations WHERE id = $1
`

func (q *Queries) GetGeneration(ctx context.Context, id uuid.UUID) (Generation, error) {
	row := q.db.QueryRow(ctx, getGeneration, id)
	var i Generation
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.ParentGenerationID,
		&i.ModelID,
		&i.ProviderID,
		&i.QuotaReservationID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Retryable,
		&i.FinishReason,
		&i.ErrorCode,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
		&i.StreamOffset,
		&i.ProviderRequestID,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGenerationByIdempotencyKey = `-- name: GetGenerationByIdempotencyKey :one
SELECT id, conversation_id, user_message_id, assistant_message_id, parent_generation_id, model_id, provider_id, quota_reservation_id, idempotency_key, status, retryable, finish_reason, error_code, input_tokens, output_tokens, cached_tokens, stream_offset, provider_request_id, accepted_at, started_at, completed_at, updated_at
FROM generations
WHERE conversation_id = $1
  AND idempotency_key = $2
`

type GetGenerationByIdempotencyKeyParams struct {
	ConversationID uuid.UUID `db:"conversation_id"`
	IdempotencyKey string    `db:"idempotency_key"`
}

func (q *Queries) GetGenerationByIdempotencyKey(ctx context.Context, arg GetGenerationByIdempotencyKeyParams) (Generation, error) {
	row := q.db.QueryRow(ctx, getGenerationByIdempotencyKey, arg.ConversationID, arg.IdempotencyKey)
	var i Generation
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.ParentGenerationID,
		&i.ModelID,
		&i.ProviderID,
		&i.QuotaReservationID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Retryable,
		&i.FinishReason,
		&i.ErrorCode,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
		&i.StreamOffset,
		&i.ProviderRequestID,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestGeneration = `-- name: GetLatestGeneration :one
SELECT id, conversation_id, user_message_id, assistant_message_id, parent_generation_id, model_id, provider_id, quota_reservation_id, idempotency_key, status, retryable, finish_reason, error_code, input_tokens, output_tokens, cached_tokens, stream_offset, provider_request_id, accepted_at, started_at, completed_at, updated_at
FROM generations
WHERE conversation_id = $1
ORDER BY accepted_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestGeneration(ctx context.Context, conversationID uuid.UUID) (Generation, error) {
	row := q.db.QueryRow(ctx, getLatestGeneration, conversationID)
	var i Generation
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.ParentGenerationID,
		&i.ModelID,
		&i.ProviderID,
		&i.QuotaReservationID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Retryable,
		&i.FinishReason,
		&i.ErrorCode,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
		&i.StreamOffset,
		&i.ProviderRequestID,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestSummary = `-- name: GetLatestSummary :one
SELECT id, conversation_id, model_id, content, from_sequence, through_sequence, version, input_tokens, created_at
FROM conversation_summaries
WHERE conversation_id = $1
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetLatestSummary(ctx context.Context, conversationID uuid.UUID) (ConversationSummary, error) {
	row := q.db.QueryRow(ctx, getLatestSummary, conversationID)
	var i ConversationSummary
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ModelID,
		&i.Content,
		&i.FromSequence,
		&i.ThroughSequence,
		&i.Version,
		&i.InputTokens,
		&i.CreatedAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, conversation_id, role, content, status, sequence, created_at, updated_at FROM messages WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.Status,
		&i.Sequence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContextMessages = `-- name: ListContextMessages :many
SELECT id, conversation_id, role, content, status, sequence, created_at, updated_at
FROM messages
WHERE conversation_id = $1
  AND (
      role = 'user'
      OR status = 'complete'
  )
ORDER BY sequence, id
`

func (q *Queries) ListContextMessages(ctx context.Context, conversationID uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listContextMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Status,
			&i.Sequence,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationMessages = `-- name: ListConversationMessages :many
SELECT id, conversation_id, role, content, status, sequence, created_at, updated_at
FROM messages
WHERE conversation_id = $1
  AND (
      $2::integer IS NULL
      OR sequence < $2::integer
  )
ORDER BY sequence DESC, id DESC
LIMIT $3
`

type ListConversationMessagesParams struct {
	ConversationID uuid.UUID `db:"conversation_id"`
	BeforeSequence *int32    `db:"before_sequence"`
	PageSize       int32     `db:"page_size"`
}

func (q *Queries) ListConversationMessages(ctx context.Context, arg ListConversationMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listConversationMessages, arg.ConversationID, arg.BeforeSequence, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Status,
			&i.Sequence,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGenerationStreaming = `-- name: MarkGenerationStreaming :one
UPDATE generations
SET status = 'streaming',
    started_at = COALESCE(started_at, $1),
    updated_at = $1
WHERE id = $2
  AND status = 'accepted'
RETURNING id, conversation_id, user_message_id, assistant_message_id, parent_generation_id, model_id, provider_id, quota_reservation_id, idempotency_key, status, retryable, finish_reason, error_code, input_tokens, output_tokens, cached_tokens, stream_offset, provider_request_id, accepted_at, started_at, completed_at, updated_at
`

type MarkGenerationStreamingParams struct {
	NowAt pgtype.Timestamptz `db:"now_at"`
	ID    uuid.UUID          `db:"id"`
}

func (q *Queries) MarkGenerationStreaming(ctx context.Context, arg MarkGenerationStreamingParams) (Generation, error) {
	row := q.db.QueryRow(ctx, markGenerationStreaming, arg.NowAt, arg.ID)
	var i Generation
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.ParentGenerationID,
		&i.ModelID,
		&i.ProviderID,
		&i.QuotaReservationID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Retryable,
		&i.FinishReason,
		&i.ErrorCode,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
		&i.StreamOffset,
		&i.ProviderRequestID,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const nextMessageSequence = `-- name: NextMessageSequence :one
SELECT COALESCE(MAX(sequence), 0)::integer + 1
FROM messages
WHERE conversation_id = $1
`

func (q *Queries) NextMessageSequence(ctx context.Context, conversationID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextMessageSequence, conversationID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
