// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGuestConversation = `-- name: CreateGuestConversation :one
INSERT INTO conversations (
    id, guest_session_id, title, model_id, creation_idempotency_key, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $6
)
RETURNING id, user_id, guest_session_id, title, status, created_at, updated_at, model_id, generation_state, renamed_by_user, last_message_at, deleted_at, creation_idempotency_key, deletion_idempotency_key
`

type CreateGuestConversationParams struct {
	ID             uuid.UUID          `db:"id"`
	GuestSessionID *uuid.UUID         `db:"guest_session_id"`
	Title          string             `db:"title"`
	ModelID        uuid.UUID          `db:"model_id"`
	IdempotencyKey *string            `db:"idempotency_key"`
	NowAt          pgtype.Timestamptz `db:"now_at"`
}

func (q *Queries) CreateGuestConversation(ctx context.Context, arg CreateGuestConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createGuestConversation,
		arg.ID,
		arg.GuestSessionID,
		arg.Title,
		arg.ModelID,
		arg.IdempotencyKey,
		arg.NowAt,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestSessionID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelID,
		&i.GenerationState,
		&i.RenamedByUser,
		&i.LastMessageAt,
		&i.DeletedAt,
		&i.CreationIdempotencyKey,
		&i.DeletionIdempotencyKey,
	)
	return i, err
}

const createUserConversation = `-- name: CreateUserConversation :one
INSERT INTO conversations (
    id, user_id, title, model_id, creation_idempotency_key, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $6
)
RETURNING id, user_id, guest_session_id, title, status, created_at, updated_at, model_id, generation_state, renamed_by_user, last_message_at, deleted_at, creation_idempotency_key, deletion_idempotency_key
`

type CreateUserConversationParams struct {
	ID             uuid.UUID          `db:"id"`
	UserID         *uuid.UUID         `db:"user_id"`
	Title          string             `db:"title"`
	ModelID        uuid.UUID          `db:"model_id"`
	IdempotencyKey *string            `db:"idempotency_key"`
	NowAt          pgtype.Timestamptz `db:"now_at"`
}

func (q *Queries) CreateUserConversation(ctx context.Context, arg CreateUserConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createUserConversation,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.ModelID,
		arg.IdempotencyKey,
		arg.NowAt,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestSessionID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelID,
		&i.GenerationState,
		&i.RenamedByUser,
		&i.LastMessageAt,
		&i.DeletedAt,
		&i.CreationIdempotencyKey,
		&i.DeletionIdempotencyKey,
	)
	return i, err
}

const getDeletedGuestConversationByKey = `-- name: GetDeletedGuestConversationByKey :one
SELECT id, user_id, guest_session_id, title, status, created_at, updated_at, model_id, generation_state, renamed_by_user, last_message_at, deleted_at, creation_idempotency_key, deletion_idempotency_key
FROM conversations
WHERE id = $1
  AND guest_session_id = $2
  AND deleted_at IS NOT NULL
  AND deletion_idempotency_key = $3
`

type GetDeletedGuestConversationByKeyParams struct {
	ID             uuid.UUID  `db:"id"`
	GuestSessionID *uuid.UUID `db:"guest_session_id"`
	IdempotencyKey *string    `db:"idempotency_key"`
}

func (q *Queries) GetDeletedGuestConversationByKey(ctx context.Context, arg GetDeletedGuestConversationByKeyParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getDeletedGuestConversationByKey, arg.ID, arg.GuestSessionID, arg.IdempotencyKey)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestSessionID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelID,
		&i.GenerationState,
		&i.RenamedByUser,
		&i.LastMessageAt,
		&i.DeletedAt,
		&i.CreationIdempotencyKey,
		&i.DeletionIdempotencyKey,
	)
	return i, err
}

const getDeletedUserConversationByKey = `-- name: GetDeletedUserConversationByKey :one
SELECT id, user_id, guest_session_id, title, status, created_at, updated_at, model_id, generation_state, renamed_by_user, last_message_at, deleted_at, creation_idempotency_key, deletion_idempotency_key
FROM conversations
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NOT NULL
  AND deletion_idempotency_key = $3
`

type GetDeletedUserConversationByKeyParams struct {
	ID             uuid.UUID  `db:"id"`
	UserID         *uuid.UUID `db:"user_id"`
	IdempotencyKey *string    `db:"idempotency_key"`
}

func (q *Queries) GetDeletedUserConversationByKey(ctx context.Context, arg GetDeletedUserConversationByKeyParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getDeletedUserConversationByKey, arg.ID, arg.UserID, arg.IdempotencyKey)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestSessionID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelID,
		&i.GenerationState,
		&i.RenamedByUser,
		&i.LastMessageAt,
		&i.DeletedAt,
		&i.CreationIdempotencyKey,
		&i.DeletionIdempotencyKey,
	)
	return i, err
}

const getGuestConversation = `-- name: GetGuestConversation :one
SELECT id, user_id, guest_session_id, title, status, created_at, updated_at, model_id, generation_state, renamed_by_user, last_message_at, deleted_at, creation_idempotency_key, deletion_idempotency_key
FROM conversations
WHERE id = $1
  AND guest_session_id = $2
  AND deleted_at IS NULL
`

type GetGuestConversationParams struct {
	ID             uuid.UUID  `db:"id"`
	GuestSessionID *uuid.UUID `db:"guest_session_id"`
}

func (q *Queries) GetGuestConversation(ctx context.Context, arg GetGuestConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getGuestConversation, arg.ID, arg.GuestSessionID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestSessionID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelID,
		&i.GenerationState,
		&i.RenamedByUser,
		&i.LastMessageAt,
		&i.DeletedAt,
		&i.CreationIdempotencyKey,
		&i.DeletionIdempotencyKey,
	)
	return i, err
}

const getGuestConversationByCreationKey = `-- name: GetGuestConversationByCreationKey :one
SELECT id, user_id, guest_session_id, title, status, created_at, updated_at, model_id, generation_state, renamed_by_user, last_message_at, deleted_at, creation_idempotency_key, deletion_idempotency_key
FROM conversations
WHERE guest_session_id = $1
  AND creation_idempotency_key = $2
`

type GetGuestConversationByCreationKeyParams struct {
	GuestSessionID *uuid.UUID `db:"guest_session_id"`
	IdempotencyKey *string    `db:"idempotency_key"`
}

func (q *Queries) GetGuestConversationByCreationKey(ctx context.Context, arg GetGuestConversationByCreationKeyParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getGuestConversationByCreationKey, arg.GuestSessionID, arg.IdempotencyKey)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestSessionID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelID,
		&i.GenerationState,
		&i.RenamedByUser,
		&i.LastMessageAt,
		&i.DeletedAt,
		&i.CreationIdempotencyKey,
		&i.DeletionIdempotencyKey,
	)
	return i, err
}

const getGuestConversationByOwner = `-- name: GetGuestConversationByOwner :one
SELECT id, user_id, guest_session_id, title, status, created_at, updated_at, model_id, generation_state, renamed_by_user, last_message_at, deleted_at, creation_idempotency_key, deletion_idempotency_key
FROM conversations
WHERE guest_session_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetGuestConversationByOwner(ctx context.Context, guestSessionID *uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getGuestConversationByOwner, guestSessionID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestSessionID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelID,
		&i.GenerationState,
		&i.RenamedByUser,
		&i.LastMessageAt,
		&i.DeletedAt,
		&i.CreationIdempotencyKey,
		&i.DeletionIdempotencyKey,
	)
	return i, err
}

const getUserConversation = `-- name: GetUserConversation :one
SELECT id, user_id, guest_session_id, title, status, created_at, updated_at, model_id, generation_state, renamed_by_user, last_message_at, deleted_at, creation_idempotency_key, deletion_idempotency_key
FROM conversations
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type GetUserConversationParams struct {
	ID     uuid.UUID  `db:"id"`
	UserID *uuid.UUID `db:"user_id"`
}

func (q *Queries) GetUserConversation(ctx context.Context, arg GetUserConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getUserConversation, arg.ID, arg.UserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestSessionID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelID,
		&i.GenerationState,
		&i.RenamedByUser,
		&i.LastMessageAt,
		&i.DeletedAt,
		&i.CreationIdempotencyKey,
		&i.DeletionIdempotencyKey,
	)
	return i, err
}

const getUserConversationByCreationKey = `-- name: GetUserConversationByCreationKey :one
SELECT id, user_id, guest_session_id, title, status, created_at, updated_at, model_id, generation_state, renamed_by_user, last_message_at, deleted_at, creation_idempotency_key, deletion_idempotency_key
FROM conversations
WHERE user_id = $1
  AND creation_idempotency_key = $2
`

type GetUserConversationByCreationKeyParams struct {
	UserID         *uuid.UUID `db:"user_id"`
	IdempotencyKey *string    `db:"idempotency_key"`
}

func (q *Queries) GetUserConversationByCreationKey(ctx context.Context, arg GetUserConversationByCreationKeyParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getUserConversationByCreationKey, arg.UserID, arg.IdempotencyKey)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestSessionID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelID,
		&i.GenerationState,
		&i.RenamedByUser,
		&i.LastMessageAt,
		&i.DeletedAt,
		&i.CreationIdempotencyKey,
		&i.DeletionIdempotencyKey,
	)
	return i, err
}

const listUserConversations = `-- name: ListUserConversations :many
SELECT id, user_id, guest_session_id, title, status, created_at, updated_at, model_id, generation_state, renamed_by_user, last_message_at, deleted_at, creation_idempotency_key, deletion_idempotency_key
FROM conversations
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($2::boolean OR status = 'active')
  AND (
      $3::text IS NULL
      OR to_tsvector('simple', title) @@ plainto_tsquery('simple', $3::text)
  )
  AND (
      $4::timestamptz IS NULL
      OR (updated_at, id) < (
          $4::timestamptz,
          $5::uuid
      )
  )
ORDER BY updated_at DESC, id DESC
LIMIT $6
`

type ListUserConversationsParams struct {
	UserID          *uuid.UUID         `db:"user_id"`
	IncludeArchived bool               `db:"include_archived"`
	Search          *string            `db:"search"`
	BeforeUpdatedAt pgtype.Timestamptz `db:"before_updated_at"`
	BeforeID        *uuid.UUID         `db:"before_id"`
	PageSize        int32              `db:"page_size"`
}

func (q *Queries) ListUserConversations(ctx context.Context, arg ListUserConversationsParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listUserConversations,
		arg.UserID,
		arg.IncludeArchived,
		arg.Search,
		arg.BeforeUpdatedAt,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GuestSessionID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModelID,
			&i.GenerationState,
			&i.RenamedByUser,
			&i.LastMessageAt,
			&i.DeletedAt,
			&i.CreationIdempotencyKey,
			&i.DeletionIdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConversationGenerationState = `-- name: SetConversationGenerationState :execrows
UPDATE conversations
SET generation_state = $1,
    updated_at = $2
WHERE id = $3
  AND deleted_at IS NULL
`

type SetConversationGenerationStateParams struct {
	State string             `db:"state"`
	NowAt pgtype.Timestamptz `db:"now_at"`
	ID    uuid.UUID          `db:"id"`
}

func (q *Queries) SetConversationGenerationState(ctx context.Context, arg SetConversationGenerationStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setConversationGenerationState, arg.State, arg.NowAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setGeneratedConversationTitle = `-- name: SetGeneratedConversationTitle :execrows
UPDATE conversations
SET title = $1,
    updated_at = $2
WHERE id = $3
  AND deleted_at IS NULL
  AND NOT renamed_by_user
  AND title = 'New conversation'
`

type SetGeneratedConversationTitleParams struct {
	Title string             `db:"title"`
	NowAt pgtype.Timestamptz `db:"now_at"`
	ID    uuid.UUID          `db:"id"`
}

func (q *Queries) SetGeneratedConversationTitle(ctx context.Context, arg SetGeneratedConversationTitleParams) (int64, error) {
	result, err := q.db.Exec(ctx, setGeneratedConversationTitle, arg.Title, arg.NowAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteGuestConversation = `-- name: SoftDeleteGuestConversation :execrows
UPDATE conversations
SET deleted_at = $1,
    deletion_idempotency_key = $2,
    updated_at = $1
WHERE id = $3
  AND guest_session_id = $4
  AND deleted_at IS NULL
  AND generation_state = 'idle'
`

type SoftDeleteGuestConversationParams struct {
	NowAt          pgtype.Timestamptz `db:"now_at"`
	IdempotencyKey *string            `db:"idempotency_key"`
	ID             uuid.UUID          `db:"id"`
	GuestSessionID *uuid.UUID         `db:"guest_session_id"`
}

func (q *Queries) SoftDeleteGuestConversation(ctx context.Context, arg SoftDeleteGuestConversationParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteGuestConversation,
		arg.NowAt,
		arg.IdempotencyKey,
		arg.ID,
		arg.GuestSessionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteUserConversation = `-- name: SoftDeleteUserConversation :execrows
UPDATE conversations
SET deleted_at = $1,
    deletion_idempotency_key = $2,
    updated_at = $1
WHERE id = $3
  AND user_id = $4
  AND deleted_at IS NULL
  AND generation_state = 'idle'
`

type SoftDeleteUserConversationParams struct {
	NowAt          pgtype.Timestamptz `db:"now_at"`
	IdempotencyKey *string            `db:"idempotency_key"`
	ID             uuid.UUID          `db:"id"`
	UserID         *uuid.UUID         `db:"user_id"`
}

func (q *Queries) SoftDeleteUserConversation(ctx context.Context, arg SoftDeleteUserConversationParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUserConversation,
		arg.NowAt,
		arg.IdempotencyKey,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateGuestConversation = `-- name: UpdateGuestConversation :one
UPDATE conversations
SET title = COALESCE($1::text, title),
    model_id = COALESCE($2::uuid, model_id),
    updated_at = $3
WHERE id = $4
  AND guest_session_id = $5
  AND deleted_at IS NULL
  AND (
      $2::uuid IS NULL
      OR generation_state = 'idle'
  )
RETURNING id, user_id, guest_session_id, title, status, created_at, updated_at, model_id, generation_state, renamed_by_user, last_message_at, deleted_at, creation_idempotency_key, deletion_idempotency_key
`

type UpdateGuestConversationParams struct {
	Title          *string            `db:"title"`
	ModelID        *uuid.UUID         `db:"model_id"`
	NowAt          pgtype.Timestamptz `db:"now_at"`
	ID             uuid.UUID          `db:"id"`
	GuestSessionID *uuid.UUID         `db:"guest_session_id"`
}

func (q *Queries) UpdateGuestConversation(ctx context.Context, arg UpdateGuestConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateGuestConversation,
		arg.Title,
		arg.ModelID,
		arg.NowAt,
		arg.ID,
		arg.GuestSessionID,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestSessionID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelID,
		&i.GenerationState,
		&i.RenamedByUser,
		&i.LastMessageAt,
		&i.DeletedAt,
		&i.CreationIdempotencyKey,
		&i.DeletionIdempotencyKey,
	)
	return i, err
}

const updateUserConversation = `-- name: UpdateUserConversation :one
UPDATE conversations
SET title = COALESCE($1::text, title),
    status = COALESCE($2::text, status),
    model_id = COALESCE($3::uuid, model_id),
    renamed_by_user = renamed_by_user OR $1::text IS NOT NULL,
    updated_at = $4
WHERE id = $5
  AND user_id = $6
  AND deleted_at IS NULL
  AND (
      $3::uuid IS NULL
      OR generation_state = 'idle'
  )
RETURNING id, user_id, guest_session_id, title, status, created_at, updated_at, model_id, generation_state, renamed_by_user, last_message_at, deleted_at, creation_idempotency_key, deletion_idempotency_key
`

type UpdateUserConversationParams struct {
	Title   *string            `db:"title"`
	Status  *string            `db:"status"`
	ModelID *uuid.UUID         `db:"model_id"`
	NowAt   pgtype.Timestamptz `db:"now_at"`
	ID      uuid.UUID          `db:"id"`
	UserID  *uuid.UUID         `db:"user_id"`
}

func (q *Queries) UpdateUserConversation(ctx context.Context, arg UpdateUserConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateUserConversation,
		arg.Title,
		arg.Status,
		arg.ModelID,
		arg.NowAt,
		arg.ID,
		arg.UserID,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestSessionID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelID,
		&i.GenerationState,
		&i.RenamedByUser,
		&i.LastMessageAt,
		&i.DeletedAt,
		&i.CreationIdempotencyKey,
		&i.DeletionIdempotencyKey,
	)
	return i, err
}
