// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guests.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adjustGuestOutputUsage = `-- name: AdjustGuestOutputUsage :exec
UPDATE guest_sessions
SET output_token_count = GREATEST(output_token_count + $1, 0),
    last_seen_at = $2
WHERE id = $3
`

type AdjustGuestOutputUsageParams struct {
	DeltaTokens int32              `db:"delta_tokens"`
	NowAt       pgtype.Timestamptz `db:"now_at"`
	GuestID     uuid.UUID          `db:"guest_id"`
}

func (q *Queries) AdjustGuestOutputUsage(ctx context.Context, arg AdjustGuestOutputUsageParams) error {
	_, err := q.db.Exec(ctx, adjustGuestOutputUsage, arg.DeltaTokens, arg.NowAt, arg.GuestID)
	return err
}

const createGuestSession = `-- name: CreateGuestSession :one
INSERT INTO guest_sessions (id, identity_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, identity_hash, prompt_count, output_token_count, first_seen_at, last_seen_at, expires_at, migrated_user_id, migrated_at
`

type CreateGuestSessionParams struct {
	ID           uuid.UUID          `db:"id"`
	IdentityHash []byte             `db:"identity_hash"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at"`
}

func (q *Queries) CreateGuestSession(ctx context.Context, arg CreateGuestSessionParams) (GuestSession, error) {
	row := q.db.QueryRow(ctx, createGuestSession, arg.ID, arg.IdentityHash, arg.ExpiresAt)
	var i GuestSession
	err := row.Scan(
		&i.ID,
		&i.IdentityHash,
		&i.PromptCount,
		&i.OutputTokenCount,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.MigratedUserID,
		&i.MigratedAt,
	)
	return i, err
}

const getGuestSession = `-- name: GetGuestSession :one
SELECT id, identity_hash, prompt_count, output_token_count, first_seen_at, last_seen_at, expires_at, migrated_user_id, migrated_at FROM guest_sessions WHERE id = $1
`

func (q *Queries) GetGuestSession(ctx context.Context, id uuid.UUID) (GuestSession, error) {
	row := q.db.QueryRow(ctx, getGuestSession, id)
	var i GuestSession
	err := row.Scan(
		&i.ID,
		&i.IdentityHash,
		&i.PromptCount,
		&i.OutputTokenCount,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.MigratedUserID,
		&i.MigratedAt,
	)
	return i, err
}

const getGuestSessionByIdentityHash = `-- name: GetGuestSessionByIdentityHash :one
SELECT id, identity_hash, prompt_count, output_token_count, first_seen_at, last_seen_at, expires_at, migrated_user_id, migrated_at FROM guest_sessions WHERE identity_hash = $1
`

func (q *Queries) GetGuestSessionByIdentityHash(ctx context.Context, identityHash []byte) (GuestSession, error) {
	row := q.db.QueryRow(ctx, getGuestSessionByIdentityHash, identityHash)
	var i GuestSession
	err := row.Scan(
		&i.ID,
		&i.IdentityHash,
		&i.PromptCount,
		&i.OutputTokenCount,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.MigratedUserID,
		&i.MigratedAt,
	)
	return i, err
}

const incrementGuestAllowance = `-- name: IncrementGuestAllowance :one
UPDATE guest_sessions
SET prompt_count = prompt_count + 1,
    output_token_count = output_token_count + $1,
    last_seen_at = $2
WHERE id = $3
  AND migrated_user_id IS NULL
  AND expires_at > $2
  AND prompt_count < $4
  AND output_token_count + $1 <= $5
RETURNING id, identity_hash, prompt_count, output_token_count, first_seen_at, last_seen_at, expires_at, migrated_user_id, migrated_at
`

type IncrementGuestAllowanceParams struct {
	OutputTokens     int32              `db:"output_tokens"`
	NowAt            pgtype.Timestamptz `db:"now_at"`
	GuestID          uuid.UUID          `db:"guest_id"`
	MessageLimit     int32              `db:"message_limit"`
	OutputTokenLimit int32              `db:"output_token_limit"`
}

func (q *Queries) IncrementGuestAllowance(ctx context.Context, arg IncrementGuestAllowanceParams) (GuestSession, error) {
	row := q.db.QueryRow(ctx, incrementGuestAllowance,
		arg.OutputTokens,
		arg.NowAt,
		arg.GuestID,
		arg.MessageLimit,
		arg.OutputTokenLimit,
	)
	var i GuestSession
	err := row.Scan(
		&i.ID,
		&i.IdentityHash,
		&i.PromptCount,
		&i.OutputTokenCount,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.MigratedUserID,
		&i.MigratedAt,
	)
	return i, err
}

const lockGuestSession = `-- name: LockGuestSession :one
SELECT id, identity_hash, prompt_count, output_token_count, first_seen_at, last_seen_at, expires_at, migrated_user_id, migrated_at FROM guest_sessions WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockGuestSession(ctx context.Context, id uuid.UUID) (GuestSession, error) {
	row := q.db.QueryRow(ctx, lockGuestSession, id)
	var i GuestSession
	err := row.Scan(
		&i.ID,
		&i.IdentityHash,
		&i.PromptCount,
		&i.OutputTokenCount,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.MigratedUserID,
		&i.MigratedAt,
	)
	return i, err
}

const markGuestMigrated = `-- name: MarkGuestMigrated :execrows
UPDATE guest_sessions
SET migrated_user_id = $2, migrated_at = $3, last_seen_at = $3
WHERE id = $1 AND migrated_user_id IS NULL
`

type MarkGuestMigratedParams struct {
	ID             uuid.UUID          `db:"id"`
	MigratedUserID *uuid.UUID         `db:"migrated_user_id"`
	MigratedAt     pgtype.Timestamptz `db:"migrated_at"`
}

func (q *Queries) MarkGuestMigrated(ctx context.Context, arg MarkGuestMigratedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markGuestMigrated, arg.ID, arg.MigratedUserID, arg.MigratedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const migrateGuestConversations = `-- name: MigrateGuestConversations :execrows
UPDATE conversations
SET user_id = $2, guest_session_id = NULL, updated_at = $3
WHERE guest_session_id = $1
`

type MigrateGuestConversationsParams struct {
	GuestSessionID *uuid.UUID         `db:"guest_session_id"`
	UserID         *uuid.UUID         `db:"user_id"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at"`
}

func (q *Queries) MigrateGuestConversations(ctx context.Context, arg MigrateGuestConversationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, migrateGuestConversations, arg.GuestSessionID, arg.UserID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchGuestSession = `-- name: TouchGuestSession :exec
UPDATE guest_sessions SET last_seen_at = $2 WHERE id = $1
`

type TouchGuestSessionParams struct {
	ID         uuid.UUID          `db:"id"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at"`
}

func (q *Queries) TouchGuestSession(ctx context.Context, arg TouchGuestSessionParams) error {
	_, err := q.db.Exec(ctx, touchGuestSession, arg.ID, arg.LastSeenAt)
	return err
}
