// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_sessions (
    id, user_id, family_id, device_label, refresh_expires_at, recent_auth_at
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, family_id, device_label, token_version, refresh_expires_at, recent_auth_at, last_seen_at, revoked_at, reuse_detected_at, created_at
`

type CreateAuthSessionParams struct {
	ID               uuid.UUID          `db:"id"`
	UserID           uuid.UUID          `db:"user_id"`
	FamilyID         uuid.UUID          `db:"family_id"`
	DeviceLabel      *string            `db:"device_label"`
	RefreshExpiresAt pgtype.Timestamptz `db:"refresh_expires_at"`
	RecentAuthAt     pgtype.Timestamptz `db:"recent_auth_at"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.ID,
		arg.UserID,
		arg.FamilyID,
		arg.DeviceLabel,
		arg.RefreshExpiresAt,
		arg.RecentAuthAt,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.DeviceLabel,
		&i.TokenVersion,
		&i.RefreshExpiresAt,
		&i.RecentAuthAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.ReuseDetectedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createGoogleIdentity = `-- name: CreateGoogleIdentity :exec
INSERT INTO user_identities (id, user_id, provider, provider_subject, verified_email)
VALUES ($1, $2, 'google', $3, $4)
`

type CreateGoogleIdentityParams struct {
	ID              uuid.UUID `db:"id"`
	UserID          uuid.UUID `db:"user_id"`
	ProviderSubject string    `db:"provider_subject"`
	VerifiedEmail   string    `db:"verified_email"`
}

func (q *Queries) CreateGoogleIdentity(ctx context.Context, arg CreateGoogleIdentityParams) error {
	_, err := q.db.Exec(ctx, createGoogleIdentity,
		arg.ID,
		arg.UserID,
		arg.ProviderSubject,
		arg.VerifiedEmail,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, display_name, avatar_url, locale, role)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, display_name, avatar_url, locale, role, plan, status, token_version, created_at, updated_at, version
`

type CreateUserParams struct {
	ID          uuid.UUID `db:"id"`
	Email       string    `db:"email"`
	DisplayName string    `db:"display_name"`
	AvatarUrl   *string   `db:"avatar_url"`
	Locale      string    `db:"locale"`
	Role        string    `db:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Locale,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Locale,
		&i.Role,
		&i.Plan,
		&i.Status,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, display_name, avatar_url, locale, role, plan, status, token_version, created_at, updated_at, version FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) FindUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Locale,
		&i.Role,
		&i.Plan,
		&i.Status,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const findUserByGoogleSubject = `-- name: FindUserByGoogleSubject :one
SELECT users.id, users.email, users.display_name, users.avatar_url, users.locale, users.role, users.plan, users.status, users.token_version, users.created_at, users.updated_at, users.version
FROM users
JOIN user_identities ON user_identities.user_id = users.id
WHERE user_identities.provider = 'google'
  AND user_identities.provider_subject = $1
`

type FindUserByGoogleSubjectRow struct {
	User User `db:"user"`
}

func (q *Queries) FindUserByGoogleSubject(ctx context.Context, providerSubject string) (FindUserByGoogleSubjectRow, error) {
	row := q.db.QueryRow(ctx, findUserByGoogleSubject, providerSubject)
	var i FindUserByGoogleSubjectRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Email,
		&i.User.DisplayName,
		&i.User.AvatarUrl,
		&i.User.Locale,
		&i.User.Role,
		&i.User.Plan,
		&i.User.Status,
		&i.User.TokenVersion,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.Version,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, email, display_name, avatar_url, locale, role, plan, status, token_version, created_at, updated_at, version FROM users WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Locale,
		&i.Role,
		&i.Plan,
		&i.Status,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getAuthSession = `-- name: GetAuthSession :one
SELECT id, user_id, family_id, device_label, token_version, refresh_expires_at, recent_auth_at, last_seen_at, revoked_at, reuse_detected_at, created_at FROM auth_sessions WHERE id = $1
`

func (q *Queries) GetAuthSession(ctx context.Context, id uuid.UUID) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getAuthSession, id)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.DeviceLabel,
		&i.TokenVersion,
		&i.RefreshExpiresAt,
		&i.RecentAuthAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.ReuseDetectedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertAdminAudit = `-- name: InsertAdminAudit :exec
INSERT INTO admin_audit_log (
    id, actor_user_id, action, target_type, target_id, before_value, after_value, request_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAdminAuditParams struct {
	ID          uuid.UUID  `db:"id"`
	ActorUserID *uuid.UUID `db:"actor_user_id"`
	Action      string     `db:"action"`
	TargetType  string     `db:"target_type"`
	TargetID    string     `db:"target_id"`
	BeforeValue []byte     `db:"before_value"`
	AfterValue  []byte     `db:"after_value"`
	RequestID   *string    `db:"request_id"`
}

func (q *Queries) InsertAdminAudit(ctx context.Context, arg InsertAdminAuditParams) error {
	_, err := q.db.Exec(ctx, insertAdminAudit,
		arg.ID,
		arg.ActorUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.BeforeValue,
		arg.AfterValue,
		arg.RequestID,
	)
	return err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO auth_refresh_tokens (token_hash, session_id, expires_at)
VALUES ($1, $2, $3)
`

type InsertRefreshTokenParams struct {
	TokenHash []byte             `db:"token_hash"`
	SessionID uuid.UUID          `db:"session_id"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken, arg.TokenHash, arg.SessionID, arg.ExpiresAt)
	return err
}

const listAuthSessions = `-- name: ListAuthSessions :many
SELECT id, user_id, family_id, device_label, token_version, refresh_expires_at, recent_auth_at, last_seen_at, revoked_at, reuse_detected_at, created_at FROM auth_sessions
WHERE user_id = $1 AND revoked_at IS NULL AND refresh_expires_at > $2
ORDER BY created_at DESC, id DESC
`

type ListAuthSessionsParams struct {
	UserID           uuid.UUID          `db:"user_id"`
	RefreshExpiresAt pgtype.Timestamptz `db:"refresh_expires_at"`
}

func (q *Queries) ListAuthSessions(ctx context.Context, arg ListAuthSessionsParams) ([]AuthSession, error) {
	rows, err := q.db.Query(ctx, listAuthSessions, arg.UserID, arg.RefreshExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthSession{}
	for rows.Next() {
		var i AuthSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FamilyID,
			&i.DeviceLabel,
			&i.TokenVersion,
			&i.RefreshExpiresAt,
			&i.RecentAuthAt,
			&i.LastSeenAt,
			&i.RevokedAt,
			&i.ReuseDetectedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRefreshToken = `-- name: LockRefreshToken :one
SELECT token.token_hash, token.session_id, token.created_at, token.expires_at, token.used_at, session.user_id, session.family_id, session.token_version,
       session.revoked_at, session.refresh_expires_at
FROM auth_refresh_tokens AS token
JOIN auth_sessions AS session ON session.id = token.session_id
WHERE token.token_hash = $1
FOR UPDATE OF token, session
`

type LockRefreshTokenRow struct {
	TokenHash        []byte             `db:"token_hash"`
	SessionID        uuid.UUID          `db:"session_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at"`
	UsedAt           pgtype.Timestamptz `db:"used_at"`
	UserID           uuid.UUID          `db:"user_id"`
	FamilyID         uuid.UUID          `db:"family_id"`
	TokenVersion     int32              `db:"token_version"`
	RevokedAt        pgtype.Timestamptz `db:"revoked_at"`
	RefreshExpiresAt pgtype.Timestamptz `db:"refresh_expires_at"`
}

func (q *Queries) LockRefreshToken(ctx context.Context, tokenHash []byte) (LockRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, lockRefreshToken, tokenHash)
	var i LockRefreshTokenRow
	err := row.Scan(
		&i.TokenHash,
		&i.SessionID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UserID,
		&i.FamilyID,
		&i.TokenVersion,
		&i.RevokedAt,
		&i.RefreshExpiresAt,
	)
	return i, err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :execrows
UPDATE auth_refresh_tokens
SET used_at = $2
WHERE token_hash = $1 AND used_at IS NULL
`

type MarkRefreshTokenUsedParams struct {
	TokenHash []byte             `db:"token_hash"`
	UsedAt    pgtype.Timestamptz `db:"used_at"`
}

func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRefreshTokenUsed, arg.TokenHash, arg.UsedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const promoteBootstrapAdmin = `-- name: PromoteBootstrapAdmin :execrows
UPDATE users SET role = 'admin', updated_at = $2
WHERE id = $1 AND role <> 'admin'
`

type PromoteBootstrapAdminParams struct {
	ID        uuid.UUID          `db:"id"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
}

func (q *Queries) PromoteBootstrapAdmin(ctx context.Context, arg PromoteBootstrapAdminParams) (int64, error) {
	result, err := q.db.Exec(ctx, promoteBootstrapAdmin, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordTermsAcceptance = `-- name: RecordTermsAcceptance :exec
INSERT INTO terms_acceptances (user_id, terms_version, privacy_version, ip_hash)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type RecordTermsAcceptanceParams struct {
	UserID         uuid.UUID `db:"user_id"`
	TermsVersion   string    `db:"terms_version"`
	PrivacyVersion string    `db:"privacy_version"`
	IpHash         []byte    `db:"ip_hash"`
}

func (q *Queries) RecordTermsAcceptance(ctx context.Context, arg RecordTermsAcceptanceParams) error {
	_, err := q.db.Exec(ctx, recordTermsAcceptance,
		arg.UserID,
		arg.TermsVersion,
		arg.PrivacyVersion,
		arg.IpHash,
	)
	return err
}

const revokeAuthSession = `-- name: RevokeAuthSession :execrows
UPDATE auth_sessions
SET revoked_at = COALESCE(revoked_at, $3), token_version = token_version + 1
WHERE id = $1 AND user_id = $2
`

type RevokeAuthSessionParams struct {
	ID        uuid.UUID          `db:"id"`
	UserID    uuid.UUID          `db:"user_id"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at"`
}

func (q *Queries) RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAuthSession, arg.ID, arg.UserID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionFamily = `-- name: RevokeSessionFamily :exec
UPDATE auth_sessions
SET revoked_at = COALESCE(revoked_at, $2),
    reuse_detected_at = COALESCE(reuse_detected_at, $2),
    token_version = token_version + 1
WHERE family_id = $1
`

type RevokeSessionFamilyParams struct {
	FamilyID  uuid.UUID          `db:"family_id"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at"`
}

func (q *Queries) RevokeSessionFamily(ctx context.Context, arg RevokeSessionFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeSessionFamily, arg.FamilyID, arg.RevokedAt)
	return err
}

const touchAuthSession = `-- name: TouchAuthSession :exec
UPDATE auth_sessions SET last_seen_at = $2 WHERE id = $1
`

type TouchAuthSessionParams struct {
	ID         uuid.UUID          `db:"id"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at"`
}

func (q *Queries) TouchAuthSession(ctx context.Context, arg TouchAuthSessionParams) error {
	_, err := q.db.Exec(ctx, touchAuthSession, arg.ID, arg.LastSeenAt)
	return err
}

const updateUserLocale = `-- name: UpdateUserLocale :one
UPDATE users
SET locale = $2, updated_at = now(), version = version + 1
WHERE id = $1
RETURNING id, email, display_name, avatar_url, locale, role, plan, status, token_version, created_at, updated_at, version
`

type UpdateUserLocaleParams struct {
	ID     uuid.UUID `db:"id"`
	Locale string    `db:"locale"`
}

func (q *Queries) UpdateUserLocale(ctx context.Context, arg UpdateUserLocaleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLocale, arg.ID, arg.Locale)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Locale,
		&i.Role,
		&i.Plan,
		&i.Status,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
