// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAuditLog struct {
	ID          uuid.UUID          `db:"id"`
	ActorUserID *uuid.UUID         `db:"actor_user_id"`
	Action      string             `db:"action"`
	TargetType  string             `db:"target_type"`
	TargetID    string             `db:"target_id"`
	BeforeValue []byte             `db:"before_value"`
	AfterValue  []byte             `db:"after_value"`
	RequestID   *string            `db:"request_id"`
	OccurredAt  pgtype.Timestamptz `db:"occurred_at"`
}

type AuthRefreshToken struct {
	TokenHash []byte             `db:"token_hash"`
	SessionID uuid.UUID          `db:"session_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at"`
	UsedAt    pgtype.Timestamptz `db:"used_at"`
}

type AuthSession struct {
	ID               uuid.UUID          `db:"id"`
	UserID           uuid.UUID          `db:"user_id"`
	FamilyID         uuid.UUID          `db:"family_id"`
	DeviceLabel      *string            `db:"device_label"`
	TokenVersion     int32              `db:"token_version"`
	RefreshExpiresAt pgtype.Timestamptz `db:"refresh_expires_at"`
	RecentAuthAt     pgtype.Timestamptz `db:"recent_auth_at"`
	LastSeenAt       pgtype.Timestamptz `db:"last_seen_at"`
	RevokedAt        pgtype.Timestamptz `db:"revoked_at"`
	ReuseDetectedAt  pgtype.Timestamptz `db:"reuse_detected_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at"`
}

type Conversation struct {
	ID             uuid.UUID          `db:"id"`
	UserID         *uuid.UUID         `db:"user_id"`
	GuestSessionID *uuid.UUID         `db:"guest_session_id"`
	Title          string             `db:"title"`
	Status         string             `db:"status"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at"`
}

type DailyUsage struct {
	ActorType        string             `db:"actor_type"`
	ActorID          uuid.UUID          `db:"actor_id"`
	UsageDate        pgtype.Date        `db:"usage_date"`
	MessagesUsed     int32              `db:"messages_used"`
	OutputTokensUsed int64              `db:"output_tokens_used"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at"`
}

type GlazzMigrationChecksum struct {
	Version    int64              `db:"version"`
	Checksum   string             `db:"checksum"`
	RecordedAt pgtype.Timestamptz `db:"recorded_at"`
}

type GuestSession struct {
	ID               uuid.UUID          `db:"id"`
	IdentityHash     []byte             `db:"identity_hash"`
	PromptCount      int32              `db:"prompt_count"`
	OutputTokenCount int32              `db:"output_token_count"`
	FirstSeenAt      pgtype.Timestamptz `db:"first_seen_at"`
	LastSeenAt       pgtype.Timestamptz `db:"last_seen_at"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at"`
	MigratedUserID   *uuid.UUID         `db:"migrated_user_id"`
	MigratedAt       pgtype.Timestamptz `db:"migrated_at"`
}

type OutboxEvent struct {
	ID             uuid.UUID          `db:"id"`
	EventType      string             `db:"event_type"`
	Payload        []byte             `db:"payload"`
	IdempotencyKey string             `db:"idempotency_key"`
	Attempts       int32              `db:"attempts"`
	AvailableAt    pgtype.Timestamptz `db:"available_at"`
	LockedAt       pgtype.Timestamptz `db:"locked_at"`
	LockedBy       *string            `db:"locked_by"`
	ProcessedAt    pgtype.Timestamptz `db:"processed_at"`
	DeadLetteredAt pgtype.Timestamptz `db:"dead_lettered_at"`
	LastErrorClass *string            `db:"last_error_class"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
}

type OutboxReceipt struct {
	EventID     uuid.UUID          `db:"event_id"`
	HandlerName string             `db:"handler_name"`
	CompletedAt pgtype.Timestamptz `db:"completed_at"`
}

type QuotaReservation struct {
	ID                   uuid.UUID          `db:"id"`
	ActorType            string             `db:"actor_type"`
	ActorID              uuid.UUID          `db:"actor_id"`
	UsageDate            pgtype.Date        `db:"usage_date"`
	ReservedOutputTokens int32              `db:"reserved_output_tokens"`
	ActualOutputTokens   *int32             `db:"actual_output_tokens"`
	Status               string             `db:"status"`
	CreatedAt            pgtype.Timestamptz `db:"created_at"`
	SettledAt            pgtype.Timestamptz `db:"settled_at"`
}

type TermsAcceptance struct {
	UserID         uuid.UUID          `db:"user_id"`
	TermsVersion   string             `db:"terms_version"`
	PrivacyVersion string             `db:"privacy_version"`
	IpHash         []byte             `db:"ip_hash"`
	AcceptedAt     pgtype.Timestamptz `db:"accepted_at"`
}

type User struct {
	ID           uuid.UUID          `db:"id"`
	Email        string             `db:"email"`
	DisplayName  string             `db:"display_name"`
	AvatarUrl    *string            `db:"avatar_url"`
	Locale       string             `db:"locale"`
	Role         string             `db:"role"`
	Plan         string             `db:"plan"`
	Status       string             `db:"status"`
	TokenVersion int32              `db:"token_version"`
	CreatedAt    pgtype.Timestamptz `db:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at"`
}

type UserIdentity struct {
	ID              uuid.UUID          `db:"id"`
	UserID          uuid.UUID          `db:"user_id"`
	Provider        string             `db:"provider"`
	ProviderSubject string             `db:"provider_subject"`
	VerifiedEmail   string             `db:"verified_email"`
	CreatedAt       pgtype.Timestamptz `db:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at"`
}
