// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: models.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDiscoveredModel = `-- name: CreateDiscoveredModel :one
INSERT INTO models (
    id, slug, name, description, context_window, max_output_tokens,
    capabilities, enabled, available, supported, audience, default_for,
    sort_order, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    false, false, true, ARRAY['user']::text[], '{}'::text[],
    $8, $9, $9
)
RETURNING id, slug, name, description, context_window, max_output_tokens, capabilities, enabled, available, supported, audience, default_for, sort_order, version, created_at, updated_at
`

type CreateDiscoveredModelParams struct {
	ID              uuid.UUID          `db:"id"`
	Slug            string             `db:"slug"`
	Name            string             `db:"name"`
	Description     string             `db:"description"`
	ContextWindow   int32              `db:"context_window"`
	MaxOutputTokens int32              `db:"max_output_tokens"`
	Capabilities    []byte             `db:"capabilities"`
	SortOrder       int32              `db:"sort_order"`
	NowAt           pgtype.Timestamptz `db:"now_at"`
}

func (q *Queries) CreateDiscoveredModel(ctx context.Context, arg CreateDiscoveredModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, createDiscoveredModel,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.ContextWindow,
		arg.MaxOutputTokens,
		arg.Capabilities,
		arg.SortOrder,
		arg.NowAt,
	)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.Capabilities,
		&i.Enabled,
		&i.Available,
		&i.Supported,
		&i.Audience,
		&i.DefaultFor,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultModel = `-- name: GetDefaultModel :one
SELECT id, slug, name, description, context_window, max_output_tokens, capabilities, enabled, available, supported, audience, default_for, sort_order, version, created_at, updated_at
FROM models
WHERE models.enabled
  AND models.available
  AND models.supported
  AND $1::text = ANY(models.default_for)
  AND EXISTS (
    SELECT 1
    FROM provider_models
    JOIN providers ON providers.id = provider_models.provider_id
    WHERE provider_models.model_id = models.id
      AND provider_models.available
      AND providers.enabled
      AND providers.health_status <> 'unavailable'
  )
`

func (q *Queries) GetDefaultModel(ctx context.Context, actorType string) (Model, error) {
	row := q.db.QueryRow(ctx, getDefaultModel, actorType)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.Capabilities,
		&i.Enabled,
		&i.Available,
		&i.Supported,
		&i.Audience,
		&i.DefaultFor,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelBySlug = `-- name: GetModelBySlug :one
SELECT id, slug, name, description, context_window, max_output_tokens, capabilities, enabled, available, supported, audience, default_for, sort_order, version, created_at, updated_at FROM models WHERE slug = $1
`

func (q *Queries) GetModelBySlug(ctx context.Context, slug string) (Model, error) {
	row := q.db.QueryRow(ctx, getModelBySlug, slug)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.Capabilities,
		&i.Enabled,
		&i.Available,
		&i.Supported,
		&i.Audience,
		&i.DefaultFor,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderByCode = `-- name: GetProviderByCode :one
SELECT id, code, display_name, adapter, enabled, health_status, settings, version, created_at, updated_at FROM providers WHERE code = $1
`

func (q *Queries) GetProviderByCode(ctx context.Context, code string) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByCode, code)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DisplayName,
		&i.Adapter,
		&i.Enabled,
		&i.HealthStatus,
		&i.Settings,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderForModel = `-- name: GetProviderForModel :one
SELECT
    provider_models.provider_id,
    provider_models.model_id,
    provider_models.provider_model_id,
    provider_models.available AS mapping_available,
    provider_models.metadata,
    provider_models.synced_at,
    providers.code AS provider_code,
    providers.adapter,
    providers.enabled AS provider_enabled,
    providers.health_status,
    providers.settings
FROM provider_models
JOIN providers ON providers.id = provider_models.provider_id
WHERE provider_models.model_id = $1
  AND provider_models.available
  AND providers.enabled
  AND providers.health_status <> 'unavailable'
ORDER BY providers.code
LIMIT 1
`

type GetProviderForModelRow struct {
	ProviderID       uuid.UUID          `db:"provider_id"`
	ModelID          uuid.UUID          `db:"model_id"`
	ProviderModelID  string             `db:"provider_model_id"`
	MappingAvailable bool               `db:"mapping_available"`
	Metadata         []byte             `db:"metadata"`
	SyncedAt         pgtype.Timestamptz `db:"synced_at"`
	ProviderCode     string             `db:"provider_code"`
	Adapter          string             `db:"adapter"`
	ProviderEnabled  bool               `db:"provider_enabled"`
	HealthStatus     string             `db:"health_status"`
	Settings         []byte             `db:"settings"`
}

func (q *Queries) GetProviderForModel(ctx context.Context, modelID uuid.UUID) (GetProviderForModelRow, error) {
	row := q.db.QueryRow(ctx, getProviderForModel, modelID)
	var i GetProviderForModelRow
	err := row.Scan(
		&i.ProviderID,
		&i.ModelID,
		&i.ProviderModelID,
		&i.MappingAvailable,
		&i.Metadata,
		&i.SyncedAt,
		&i.ProviderCode,
		&i.Adapter,
		&i.ProviderEnabled,
		&i.HealthStatus,
		&i.Settings,
	)
	return i, err
}

const getSelectableModel = `-- name: GetSelectableModel :one
SELECT id, slug, name, description, context_window, max_output_tokens, capabilities, enabled, available, supported, audience, default_for, sort_order, version, created_at, updated_at
FROM models
WHERE models.id = $1
  AND models.enabled
  AND models.available
  AND models.supported
  AND $2::text = ANY(models.audience)
  AND (
    $2::text <> 'guest'
    OR $2::text = ANY(models.default_for)
  )
  AND EXISTS (
    SELECT 1
    FROM provider_models
    JOIN providers ON providers.id = provider_models.provider_id
    WHERE provider_models.model_id = models.id
      AND provider_models.available
      AND providers.enabled
      AND providers.health_status <> 'unavailable'
  )
`

type GetSelectableModelParams struct {
	ModelID   uuid.UUID `db:"model_id"`
	ActorType string    `db:"actor_type"`
}

func (q *Queries) GetSelectableModel(ctx context.Context, arg GetSelectableModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, getSelectableModel, arg.ModelID, arg.ActorType)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.Capabilities,
		&i.Enabled,
		&i.Available,
		&i.Supported,
		&i.Audience,
		&i.DefaultFor,
		&i.SortOrder,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviderModelMappings = `-- name: ListProviderModelMappings :many
SELECT provider_id, model_id, provider_model_id, available, metadata, synced_at FROM provider_models
WHERE provider_id = $1
ORDER BY provider_model_id, model_id
`

func (q *Queries) ListProviderModelMappings(ctx context.Context, providerID uuid.UUID) ([]ProviderModel, error) {
	rows, err := q.db.Query(ctx, listProviderModelMappings, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderModel{}
	for rows.Next() {
		var i ProviderModel
		if err := rows.Scan(
			&i.ProviderID,
			&i.ModelID,
			&i.ProviderModelID,
			&i.Available,
			&i.Metadata,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicModels = `-- name: ListPublicModels :many
SELECT id, slug, name, description, context_window, max_output_tokens, capabilities, enabled, available, supported, audience, default_for, sort_order, version, created_at, updated_at
FROM models
WHERE models.enabled
  AND models.available
  AND models.supported
  AND $1::text = ANY(models.audience)
  AND (
    $1::text <> 'guest'
    OR $1::text = ANY(models.default_for)
  )
  AND EXISTS (
    SELECT 1
    FROM provider_models
    JOIN providers ON providers.id = provider_models.provider_id
    WHERE provider_models.model_id = models.id
      AND provider_models.available
      AND providers.enabled
      AND providers.health_status <> 'unavailable'
  )
ORDER BY models.sort_order, models.name, models.id
`

func (q *Queries) ListPublicModels(ctx context.Context, actorType string) ([]Model, error) {
	rows, err := q.db.Query(ctx, listPublicModels, actorType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Model{}
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.Capabilities,
			&i.Enabled,
			&i.Available,
			&i.Supported,
			&i.Audience,
			&i.DefaultFor,
			&i.SortOrder,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProviderModelsUnavailable = `-- name: MarkProviderModelsUnavailable :exec
UPDATE provider_models
SET available = false,
    synced_at = $1
WHERE provider_id = $2
  AND NOT (provider_model_id = ANY($3::text[]))
`

type MarkProviderModelsUnavailableParams struct {
	SyncedAt        pgtype.Timestamptz `db:"synced_at"`
	ProviderID      uuid.UUID          `db:"provider_id"`
	PresentModelIds []string           `db:"present_model_ids"`
}

func (q *Queries) MarkProviderModelsUnavailable(ctx context.Context, arg MarkProviderModelsUnavailableParams) error {
	_, err := q.db.Exec(ctx, markProviderModelsUnavailable, arg.SyncedAt, arg.ProviderID, arg.PresentModelIds)
	return err
}

const refreshModelAvailability = `-- name: RefreshModelAvailability :execrows
UPDATE models
SET available = EXISTS (
        SELECT 1
        FROM provider_models
        JOIN providers ON providers.id = provider_models.provider_id
        WHERE provider_models.model_id = models.id
          AND provider_models.available
          AND providers.enabled
    ),
    version = version + 1,
    updated_at = $1
WHERE available IS DISTINCT FROM EXISTS (
    SELECT 1
    FROM provider_models
    JOIN providers ON providers.id = provider_models.provider_id
    WHERE provider_models.model_id = models.id
      AND provider_models.available
      AND providers.enabled
)
`

func (q *Queries) RefreshModelAvailability(ctx context.Context, nowAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, refreshModelAvailability, nowAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setProviderEnabledByCode = `-- name: SetProviderEnabledByCode :exec
UPDATE providers
SET enabled = $1,
    version = version + 1,
    updated_at = $2
WHERE code = $3
  AND enabled IS DISTINCT FROM $1
`

type SetProviderEnabledByCodeParams struct {
	Enabled bool               `db:"enabled"`
	NowAt   pgtype.Timestamptz `db:"now_at"`
	Code    string             `db:"code"`
}

func (q *Queries) SetProviderEnabledByCode(ctx context.Context, arg SetProviderEnabledByCodeParams) error {
	_, err := q.db.Exec(ctx, setProviderEnabledByCode, arg.Enabled, arg.NowAt, arg.Code)
	return err
}

const upsertProvider = `-- name: UpsertProvider :one
INSERT INTO providers (
    id, code, display_name, adapter, enabled, health_status, settings, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
ON CONFLICT (code) DO UPDATE
SET display_name = EXCLUDED.display_name,
    adapter = EXCLUDED.adapter,
    enabled = EXCLUDED.enabled,
    health_status = EXCLUDED.health_status,
    settings = EXCLUDED.settings,
    version = providers.version + 1,
    updated_at = EXCLUDED.updated_at
RETURNING id, code, display_name, adapter, enabled, health_status, settings, version, created_at, updated_at
`

type UpsertProviderParams struct {
	ID           uuid.UUID          `db:"id"`
	Code         string             `db:"code"`
	DisplayName  string             `db:"display_name"`
	Adapter      string             `db:"adapter"`
	Enabled      bool               `db:"enabled"`
	HealthStatus string             `db:"health_status"`
	Settings     []byte             `db:"settings"`
	NowAt        pgtype.Timestamptz `db:"now_at"`
}

func (q *Queries) UpsertProvider(ctx context.Context, arg UpsertProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, upsertProvider,
		arg.ID,
		arg.Code,
		arg.DisplayName,
		arg.Adapter,
		arg.Enabled,
		arg.HealthStatus,
		arg.Settings,
		arg.NowAt,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DisplayName,
		&i.Adapter,
		&i.Enabled,
		&i.HealthStatus,
		&i.Settings,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProviderModel = `-- name: UpsertProviderModel :exec
INSERT INTO provider_models (
    provider_id, model_id, provider_model_id, available, metadata, synced_at
) VALUES (
    $1, $2, $3,
    true, $4, $5
)
ON CONFLICT (provider_id, model_id) DO UPDATE
SET provider_model_id = EXCLUDED.provider_model_id,
    available = true,
    metadata = EXCLUDED.metadata,
    synced_at = EXCLUDED.synced_at
`

type UpsertProviderModelParams struct {
	ProviderID      uuid.UUID          `db:"provider_id"`
	ModelID         uuid.UUID          `db:"model_id"`
	ProviderModelID string             `db:"provider_model_id"`
	Metadata        []byte             `db:"metadata"`
	SyncedAt        pgtype.Timestamptz `db:"synced_at"`
}

func (q *Queries) UpsertProviderModel(ctx context.Context, arg UpsertProviderModelParams) error {
	_, err := q.db.Exec(ctx, upsertProviderModel,
		arg.ProviderID,
		arg.ModelID,
		arg.ProviderModelID,
		arg.Metadata,
		arg.SyncedAt,
	)
	return err
}
