// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addDailyUsage = `-- name: AddDailyUsage :one
INSERT INTO daily_usage (
    actor_type, actor_id, usage_date, messages_used, output_tokens_used, updated_at
)
VALUES (
    $1, $2, $3,
    1, $4, $5
)
ON CONFLICT (actor_type, actor_id, usage_date) DO UPDATE
SET messages_used = daily_usage.messages_used + 1,
    output_tokens_used = daily_usage.output_tokens_used + EXCLUDED.output_tokens_used,
    updated_at = EXCLUDED.updated_at
WHERE daily_usage.messages_used + 1 <= $6
  AND daily_usage.output_tokens_used + EXCLUDED.output_tokens_used <= $7
RETURNING actor_type, actor_id, usage_date, messages_used, output_tokens_used, updated_at
`

type AddDailyUsageParams struct {
	ActorType        string             `db:"actor_type"`
	ActorID          uuid.UUID          `db:"actor_id"`
	UsageDate        pgtype.Date        `db:"usage_date"`
	OutputTokens     int64              `db:"output_tokens"`
	NowAt            pgtype.Timestamptz `db:"now_at"`
	MessageLimit     int32              `db:"message_limit"`
	OutputTokenLimit int64              `db:"output_token_limit"`
}

func (q *Queries) AddDailyUsage(ctx context.Context, arg AddDailyUsageParams) (DailyUsage, error) {
	row := q.db.QueryRow(ctx, addDailyUsage,
		arg.ActorType,
		arg.ActorID,
		arg.UsageDate,
		arg.OutputTokens,
		arg.NowAt,
		arg.MessageLimit,
		arg.OutputTokenLimit,
	)
	var i DailyUsage
	err := row.Scan(
		&i.ActorType,
		&i.ActorID,
		&i.UsageDate,
		&i.MessagesUsed,
		&i.OutputTokensUsed,
		&i.UpdatedAt,
	)
	return i, err
}

const adjustDailyOutputUsage = `-- name: AdjustDailyOutputUsage :exec
UPDATE daily_usage
SET output_tokens_used = GREATEST(output_tokens_used + $1, 0),
    updated_at = $2
WHERE actor_type = $3
  AND actor_id = $4
  AND usage_date = $5
`

type AdjustDailyOutputUsageParams struct {
	DeltaTokens int64              `db:"delta_tokens"`
	NowAt       pgtype.Timestamptz `db:"now_at"`
	ActorType   string             `db:"actor_type"`
	ActorID     uuid.UUID          `db:"actor_id"`
	UsageDate   pgtype.Date        `db:"usage_date"`
}

func (q *Queries) AdjustDailyOutputUsage(ctx context.Context, arg AdjustDailyOutputUsageParams) error {
	_, err := q.db.Exec(ctx, adjustDailyOutputUsage,
		arg.DeltaTokens,
		arg.NowAt,
		arg.ActorType,
		arg.ActorID,
		arg.UsageDate,
	)
	return err
}

const claimOutboxEvents = `-- name: ClaimOutboxEvents :many
WITH candidates AS (
    SELECT candidate.id
    FROM outbox_events AS candidate
    WHERE candidate.processed_at IS NULL
      AND candidate.dead_lettered_at IS NULL
      AND candidate.available_at <= $1
      AND (candidate.locked_at IS NULL OR candidate.locked_at < $3)
    ORDER BY candidate.available_at, candidate.created_at
    LIMIT $4
    FOR UPDATE SKIP LOCKED
)
UPDATE outbox_events AS event
SET locked_at = $1,
    locked_by = $2,
    attempts = event.attempts + 1
FROM candidates
WHERE event.id = candidates.id
  AND event.processed_at IS NULL
  AND event.dead_lettered_at IS NULL
  AND (event.locked_at IS NULL OR event.locked_at < $3)
RETURNING event.id, event.event_type, event.payload, event.idempotency_key, event.attempts, event.available_at, event.locked_at, event.locked_by, event.processed_at, event.dead_lettered_at, event.last_error_class, event.created_at
`

type ClaimOutboxEventsParams struct {
	NowAt             pgtype.Timestamptz `db:"now_at"`
	WorkerID          *string            `db:"worker_id"`
	LockExpiredBefore pgtype.Timestamptz `db:"lock_expired_before"`
	BatchSize         int32              `db:"batch_size"`
}

func (q *Queries) ClaimOutboxEvents(ctx context.Context, arg ClaimOutboxEventsParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimOutboxEvents,
		arg.NowAt,
		arg.WorkerID,
		arg.LockExpiredBefore,
		arg.BatchSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.IdempotencyKey,
			&i.Attempts,
			&i.AvailableAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.ProcessedAt,
			&i.DeadLetteredAt,
			&i.LastErrorClass,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeOutboxEvent = `-- name: CompleteOutboxEvent :execrows
UPDATE outbox_events
SET processed_at = $3, locked_at = NULL, locked_by = NULL, last_error_class = NULL
WHERE id = $1 AND locked_by = $2 AND processed_at IS NULL
`

type CompleteOutboxEventParams struct {
	ID          uuid.UUID          `db:"id"`
	LockedBy    *string            `db:"locked_by"`
	ProcessedAt pgtype.Timestamptz `db:"processed_at"`
}

func (q *Queries) CompleteOutboxEvent(ctx context.Context, arg CompleteOutboxEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeOutboxEvent, arg.ID, arg.LockedBy, arg.ProcessedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countGlobalActiveReservations = `-- name: CountGlobalActiveReservations :one
SELECT COUNT(*)::bigint
FROM quota_reservations
WHERE status = 'reserved'
`

func (q *Queries) CountGlobalActiveReservations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGlobalActiveReservations)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createQuotaReservation = `-- name: CreateQuotaReservation :exec
INSERT INTO quota_reservations (
    id, actor_type, actor_id, usage_date, reserved_output_tokens, status
)
VALUES ($1, $2, $3, $4, $5, 'reserved')
`

type CreateQuotaReservationParams struct {
	ID                   uuid.UUID   `db:"id"`
	ActorType            string      `db:"actor_type"`
	ActorID              uuid.UUID   `db:"actor_id"`
	UsageDate            pgtype.Date `db:"usage_date"`
	ReservedOutputTokens int32       `db:"reserved_output_tokens"`
}

func (q *Queries) CreateQuotaReservation(ctx context.Context, arg CreateQuotaReservationParams) error {
	_, err := q.db.Exec(ctx, createQuotaReservation,
		arg.ID,
		arg.ActorType,
		arg.ActorID,
		arg.UsageDate,
		arg.ReservedOutputTokens,
	)
	return err
}

const deadLetterOutboxEvent = `-- name: DeadLetterOutboxEvent :execrows
UPDATE outbox_events
SET dead_lettered_at = $3, locked_at = NULL, locked_by = NULL, last_error_class = $4
WHERE id = $1 AND locked_by = $2 AND processed_at IS NULL
`

type DeadLetterOutboxEventParams struct {
	ID             uuid.UUID          `db:"id"`
	LockedBy       *string            `db:"locked_by"`
	DeadLetteredAt pgtype.Timestamptz `db:"dead_lettered_at"`
	LastErrorClass *string            `db:"last_error_class"`
}

func (q *Queries) DeadLetterOutboxEvent(ctx context.Context, arg DeadLetterOutboxEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, deadLetterOutboxEvent,
		arg.ID,
		arg.LockedBy,
		arg.DeadLetteredAt,
		arg.LastErrorClass,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueOutboxEvent = `-- name: EnqueueOutboxEvent :exec
INSERT INTO outbox_events (id, event_type, payload, idempotency_key, available_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (idempotency_key) DO NOTHING
`

type EnqueueOutboxEventParams struct {
	ID             uuid.UUID          `db:"id"`
	EventType      string             `db:"event_type"`
	Payload        []byte             `db:"payload"`
	IdempotencyKey string             `db:"idempotency_key"`
	AvailableAt    pgtype.Timestamptz `db:"available_at"`
}

func (q *Queries) EnqueueOutboxEvent(ctx context.Context, arg EnqueueOutboxEventParams) error {
	_, err := q.db.Exec(ctx, enqueueOutboxEvent,
		arg.ID,
		arg.EventType,
		arg.Payload,
		arg.IdempotencyKey,
		arg.AvailableAt,
	)
	return err
}

const getDailyUsage = `-- name: GetDailyUsage :one
SELECT actor_type, actor_id, usage_date, messages_used, output_tokens_used, updated_at
FROM daily_usage
WHERE actor_type = $1
  AND actor_id = $2
  AND usage_date = $3
`

type GetDailyUsageParams struct {
	ActorType string      `db:"actor_type"`
	ActorID   uuid.UUID   `db:"actor_id"`
	UsageDate pgtype.Date `db:"usage_date"`
}

func (q *Queries) GetDailyUsage(ctx context.Context, arg GetDailyUsageParams) (DailyUsage, error) {
	row := q.db.QueryRow(ctx, getDailyUsage, arg.ActorType, arg.ActorID, arg.UsageDate)
	var i DailyUsage
	err := row.Scan(
		&i.ActorType,
		&i.ActorID,
		&i.UsageDate,
		&i.MessagesUsed,
		&i.OutputTokensUsed,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutboxEventByIdempotencyKey = `-- name: GetOutboxEventByIdempotencyKey :one
SELECT id, event_type, payload, idempotency_key, attempts, available_at, locked_at, locked_by, processed_at, dead_lettered_at, last_error_class, created_at FROM outbox_events WHERE idempotency_key = $1
`

func (q *Queries) GetOutboxEventByIdempotencyKey(ctx context.Context, idempotencyKey string) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, getOutboxEventByIdempotencyKey, idempotencyKey)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Payload,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.AvailableAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.ProcessedAt,
		&i.DeadLetteredAt,
		&i.LastErrorClass,
		&i.CreatedAt,
	)
	return i, err
}

const hasOutboxReceipt = `-- name: HasOutboxReceipt :one
SELECT EXISTS (
    SELECT 1 FROM outbox_receipts WHERE event_id = $1 AND handler_name = $2
)
`

type HasOutboxReceiptParams struct {
	EventID     uuid.UUID `db:"event_id"`
	HandlerName string    `db:"handler_name"`
}

func (q *Queries) HasOutboxReceipt(ctx context.Context, arg HasOutboxReceiptParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasOutboxReceipt, arg.EventID, arg.HandlerName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lockGlobalGenerationAdmission = `-- name: LockGlobalGenerationAdmission :exec
SELECT pg_advisory_xact_lock(hashtextextended('global-generation-admission', 0))
`

func (q *Queries) LockGlobalGenerationAdmission(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockGlobalGenerationAdmission)
	return err
}

const lockQuotaReservation = `-- name: LockQuotaReservation :one
SELECT id, actor_type, actor_id, usage_date, reserved_output_tokens, actual_output_tokens, status, created_at, settled_at FROM quota_reservations WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockQuotaReservation(ctx context.Context, id uuid.UUID) (QuotaReservation, error) {
	row := q.db.QueryRow(ctx, lockQuotaReservation, id)
	var i QuotaReservation
	err := row.Scan(
		&i.ID,
		&i.ActorType,
		&i.ActorID,
		&i.UsageDate,
		&i.ReservedOutputTokens,
		&i.ActualOutputTokens,
		&i.Status,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const ping = `-- name: Ping :one
SELECT 1::integer
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const recordOutboxReceipt = `-- name: RecordOutboxReceipt :exec
INSERT INTO outbox_receipts (event_id, handler_name)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type RecordOutboxReceiptParams struct {
	EventID     uuid.UUID `db:"event_id"`
	HandlerName string    `db:"handler_name"`
}

func (q *Queries) RecordOutboxReceipt(ctx context.Context, arg RecordOutboxReceiptParams) error {
	_, err := q.db.Exec(ctx, recordOutboxReceipt, arg.EventID, arg.HandlerName)
	return err
}

const retryOutboxEvent = `-- name: RetryOutboxEvent :execrows
UPDATE outbox_events
SET available_at = $3, locked_at = NULL, locked_by = NULL, last_error_class = $4
WHERE id = $1 AND locked_by = $2 AND processed_at IS NULL
`

type RetryOutboxEventParams struct {
	ID             uuid.UUID          `db:"id"`
	LockedBy       *string            `db:"locked_by"`
	AvailableAt    pgtype.Timestamptz `db:"available_at"`
	LastErrorClass *string            `db:"last_error_class"`
}

func (q *Queries) RetryOutboxEvent(ctx context.Context, arg RetryOutboxEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryOutboxEvent,
		arg.ID,
		arg.LockedBy,
		arg.AvailableAt,
		arg.LastErrorClass,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const settleQuotaReservation = `-- name: SettleQuotaReservation :execrows
UPDATE quota_reservations
SET actual_output_tokens = $2,
    status = $3,
    settled_at = $4
WHERE id = $1 AND status = 'reserved'
`

type SettleQuotaReservationParams struct {
	ID                 uuid.UUID          `db:"id"`
	ActualOutputTokens *int32             `db:"actual_output_tokens"`
	Status             string             `db:"status"`
	SettledAt          pgtype.Timestamptz `db:"settled_at"`
}

func (q *Queries) SettleQuotaReservation(ctx context.Context, arg SettleQuotaReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, settleQuotaReservation,
		arg.ID,
		arg.ActualOutputTokens,
		arg.Status,
		arg.SettledAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
