// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: privacy.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimAccountDeletionJobs = `-- name: ClaimAccountDeletionJobs :many
WITH candidates AS (
    SELECT pending.id
    FROM account_deletion_jobs AS pending
    WHERE (
        pending.status IN ('pending', 'failed')
        OR (
            pending.status = 'processing'
            AND pending.started_at < $1::timestamptz - interval '15 minutes'
        )
    )
      AND pending.requested_at <= $2
    ORDER BY pending.requested_at, pending.id
    FOR UPDATE SKIP LOCKED
    LIMIT $3
)
UPDATE account_deletion_jobs AS jobs
SET status = 'processing',
    started_at = $1,
    attempts = attempts + 1,
    last_error_class = NULL
FROM candidates
WHERE jobs.id = candidates.id
RETURNING jobs.id, jobs.user_id, jobs.status, jobs.requested_at, jobs.due_at, jobs.started_at, jobs.completed_at, jobs.attempts, jobs.last_error_class
`

type ClaimAccountDeletionJobsParams struct {
	NowAt           pgtype.Timestamptz `db:"now_at"`
	RequestedBefore pgtype.Timestamptz `db:"requested_before"`
	BatchSize       int32              `db:"batch_size"`
}

func (q *Queries) ClaimAccountDeletionJobs(ctx context.Context, arg ClaimAccountDeletionJobsParams) ([]AccountDeletionJob, error) {
	rows, err := q.db.Query(ctx, claimAccountDeletionJobs, arg.NowAt, arg.RequestedBefore, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountDeletionJob{}
	for rows.Next() {
		var i AccountDeletionJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.RequestedAt,
			&i.DueAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Attempts,
			&i.LastErrorClass,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeAccountDeletionJob = `-- name: CompleteAccountDeletionJob :execrows
UPDATE account_deletion_jobs
SET status = 'completed',
    user_id = NULL,
    completed_at = $1,
    last_error_class = NULL
WHERE id = $2
  AND status = 'processing'
`

type CompleteAccountDeletionJobParams struct {
	NowAt pgtype.Timestamptz `db:"now_at"`
	ID    uuid.UUID          `db:"id"`
}

func (q *Queries) CompleteAccountDeletionJob(ctx context.Context, arg CompleteAccountDeletionJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeAccountDeletionJob, arg.NowAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAccountDeletionJob = `-- name: CreateAccountDeletionJob :one
INSERT INTO account_deletion_jobs (
    id, user_id, status, requested_at, due_at
) VALUES (
    $1, $2, 'pending',
    $3, $4
)
ON CONFLICT (user_id) DO UPDATE
SET user_id = EXCLUDED.user_id
RETURNING id, user_id, status, requested_at, due_at, started_at, completed_at, attempts, last_error_class
`

type CreateAccountDeletionJobParams struct {
	ID          uuid.UUID          `db:"id"`
	UserID      *uuid.UUID         `db:"user_id"`
	RequestedAt pgtype.Timestamptz `db:"requested_at"`
	DueAt       pgtype.Timestamptz `db:"due_at"`
}

func (q *Queries) CreateAccountDeletionJob(ctx context.Context, arg CreateAccountDeletionJobParams) (AccountDeletionJob, error) {
	row := q.db.QueryRow(ctx, createAccountDeletionJob,
		arg.ID,
		arg.UserID,
		arg.RequestedAt,
		arg.DueAt,
	)
	var i AccountDeletionJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.RequestedAt,
		&i.DueAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Attempts,
		&i.LastErrorClass,
	)
	return i, err
}

const deleteExpiredGuestSessions = `-- name: DeleteExpiredGuestSessions :execrows
DELETE FROM guest_sessions AS guests
WHERE guests.expires_at < $1
  AND guests.migrated_user_id IS NULL
  AND NOT EXISTS (
      SELECT 1
      FROM conversations
      JOIN generations ON generations.conversation_id = conversations.id
      WHERE conversations.guest_session_id = guests.id
        AND generations.status IN ('accepted', 'streaming')
  )
`

func (q *Queries) DeleteExpiredGuestSessions(ctx context.Context, expiredBefore pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredGuestSessions, expiredBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserForPurge = `-- name: DeleteUserForPurge :execrows
DELETE FROM users
WHERE id = $1
  AND status = 'deletion_pending'
`

func (q *Queries) DeleteUserForPurge(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserForPurge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failAccountDeletionJob = `-- name: FailAccountDeletionJob :execrows
UPDATE account_deletion_jobs
SET status = 'failed',
    last_error_class = $1
WHERE id = $2
  AND status = 'processing'
`

type FailAccountDeletionJobParams struct {
	LastErrorClass *string   `db:"last_error_class"`
	ID             uuid.UUID `db:"id"`
}

func (q *Queries) FailAccountDeletionJob(ctx context.Context, arg FailAccountDeletionJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, failAccountDeletionJob, arg.LastErrorClass, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccountDeletionJobByUser = `-- name: GetAccountDeletionJobByUser :one
SELECT id, user_id, status, requested_at, due_at, started_at, completed_at, attempts, last_error_class FROM account_deletion_jobs
WHERE user_id = $1
ORDER BY requested_at DESC
LIMIT 1
`

func (q *Queries) GetAccountDeletionJobByUser(ctx context.Context, userID *uuid.UUID) (AccountDeletionJob, error) {
	row := q.db.QueryRow(ctx, getAccountDeletionJobByUser, userID)
	var i AccountDeletionJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.RequestedAt,
		&i.DueAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Attempts,
		&i.LastErrorClass,
	)
	return i, err
}

const markUserDeletionPending = `-- name: MarkUserDeletionPending :execrows
UPDATE users
SET status = 'deletion_pending',
    token_version = token_version + 1,
    version = version + 1,
    updated_at = $1
WHERE id = $2
  AND status = 'active'
`

type MarkUserDeletionPendingParams struct {
	NowAt pgtype.Timestamptz `db:"now_at"`
	ID    uuid.UUID          `db:"id"`
}

func (q *Queries) MarkUserDeletionPending(ctx context.Context, arg MarkUserDeletionPendingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markUserDeletionPending, arg.NowAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE auth_sessions
SET revoked_at = COALESCE(revoked_at, $1),
    token_version = token_version + 1
WHERE user_id = $2
  AND revoked_at IS NULL
`

type RevokeAllUserSessionsParams struct {
	NowAt  pgtype.Timestamptz `db:"now_at"`
	UserID uuid.UUID          `db:"user_id"`
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, arg.NowAt, arg.UserID)
	return err
}
