// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddDailyUsage(ctx context.Context, arg AddDailyUsageParams) (DailyUsage, error)
	AdjustDailyOutputUsage(ctx context.Context, arg AdjustDailyOutputUsageParams) error
	AdjustGuestOutputUsage(ctx context.Context, arg AdjustGuestOutputUsageParams) error
	ClaimOutboxEvents(ctx context.Context, arg ClaimOutboxEventsParams) ([]OutboxEvent, error)
	CompleteOutboxEvent(ctx context.Context, arg CompleteOutboxEventParams) (int64, error)
	CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error)
	CreateGoogleIdentity(ctx context.Context, arg CreateGoogleIdentityParams) error
	CreateGuestSession(ctx context.Context, arg CreateGuestSessionParams) (GuestSession, error)
	CreateQuotaReservation(ctx context.Context, arg CreateQuotaReservationParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeadLetterOutboxEvent(ctx context.Context, arg DeadLetterOutboxEventParams) (int64, error)
	EnqueueOutboxEvent(ctx context.Context, arg EnqueueOutboxEventParams) error
	FindUserByEmail(ctx context.Context, lower string) (User, error)
	FindUserByGoogleSubject(ctx context.Context, providerSubject string) (FindUserByGoogleSubjectRow, error)
	FindUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetAuthSession(ctx context.Context, id uuid.UUID) (AuthSession, error)
	GetGuestSessionByIdentityHash(ctx context.Context, identityHash []byte) (GuestSession, error)
	HasOutboxReceipt(ctx context.Context, arg HasOutboxReceiptParams) (bool, error)
	IncrementGuestAllowance(ctx context.Context, arg IncrementGuestAllowanceParams) (GuestSession, error)
	InsertAdminAudit(ctx context.Context, arg InsertAdminAuditParams) error
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error
	ListAuthSessions(ctx context.Context, arg ListAuthSessionsParams) ([]AuthSession, error)
	LockGuestSession(ctx context.Context, id uuid.UUID) (GuestSession, error)
	LockQuotaReservation(ctx context.Context, id uuid.UUID) (QuotaReservation, error)
	LockRefreshToken(ctx context.Context, tokenHash []byte) (LockRefreshTokenRow, error)
	MarkGuestMigrated(ctx context.Context, arg MarkGuestMigratedParams) (int64, error)
	MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) (int64, error)
	MigrateGuestConversations(ctx context.Context, arg MigrateGuestConversationsParams) (int64, error)
	Ping(ctx context.Context) (int32, error)
	PromoteBootstrapAdmin(ctx context.Context, arg PromoteBootstrapAdminParams) (int64, error)
	RecordOutboxReceipt(ctx context.Context, arg RecordOutboxReceiptParams) error
	RecordTermsAcceptance(ctx context.Context, arg RecordTermsAcceptanceParams) error
	RetryOutboxEvent(ctx context.Context, arg RetryOutboxEventParams) (int64, error)
	RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) (int64, error)
	RevokeSessionFamily(ctx context.Context, arg RevokeSessionFamilyParams) error
	SettleQuotaReservation(ctx context.Context, arg SettleQuotaReservationParams) (int64, error)
	TouchAuthSession(ctx context.Context, arg TouchAuthSessionParams) error
	TouchGuestSession(ctx context.Context, arg TouchGuestSessionParams) error
}

var _ Querier = (*Queries)(nil)
