// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AdminModelAudience.
const (
	AdminModelAudienceGuest AdminModelAudience = "guest"
	AdminModelAudienceUser  AdminModelAudience = "user"
)

// Valid indicates whether the value is a known member of the AdminModelAudience enum.
func (e AdminModelAudience) Valid() bool {
	switch e {
	case AdminModelAudienceGuest:
		return true
	case AdminModelAudienceUser:
		return true
	default:
		return false
	}
}

// Defines values for AdminModelCapabilitiesChatCompletions.
const (
	AdminModelCapabilitiesChatCompletionsTrue AdminModelCapabilitiesChatCompletions = true
)

// Valid indicates whether the value is a known member of the AdminModelCapabilitiesChatCompletions enum.
func (e AdminModelCapabilitiesChatCompletions) Valid() bool {
	switch e {
	case AdminModelCapabilitiesChatCompletionsTrue:
		return true
	default:
		return false
	}
}

// Defines values for AdminModelDefaultFor.
const (
	AdminModelDefaultForGuest AdminModelDefaultFor = "guest"
	AdminModelDefaultForUser  AdminModelDefaultFor = "user"
)

// Valid indicates whether the value is a known member of the AdminModelDefaultFor enum.
func (e AdminModelDefaultFor) Valid() bool {
	switch e {
	case AdminModelDefaultForGuest:
		return true
	case AdminModelDefaultForUser:
		return true
	default:
		return false
	}
}

// Defines values for AdminUserStatus.
const (
	AdminUserStatusActive          AdminUserStatus = "active"
	AdminUserStatusDeletionPending AdminUserStatus = "deletion_pending"
	AdminUserStatusDisabled        AdminUserStatus = "disabled"
)

// Valid indicates whether the value is a known member of the AdminUserStatus enum.
func (e AdminUserStatus) Valid() bool {
	switch e {
	case AdminUserStatusActive:
		return true
	case AdminUserStatusDeletionPending:
		return true
	case AdminUserStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for ConversationGenerationState.
const (
	ConversationGenerationStateAccepted  ConversationGenerationState = "accepted"
	ConversationGenerationStateIdle      ConversationGenerationState = "idle"
	ConversationGenerationStateStreaming ConversationGenerationState = "streaming"
)

// Valid indicates whether the value is a known member of the ConversationGenerationState enum.
func (e ConversationGenerationState) Valid() bool {
	switch e {
	case ConversationGenerationStateAccepted:
		return true
	case ConversationGenerationStateIdle:
		return true
	case ConversationGenerationStateStreaming:
		return true
	default:
		return false
	}
}

// Defines values for ConversationStatus.
const (
	ConversationStatusActive   ConversationStatus = "active"
	ConversationStatusArchived ConversationStatus = "archived"
)

// Valid indicates whether the value is a known member of the ConversationStatus enum.
func (e ConversationStatus) Valid() bool {
	switch e {
	case ConversationStatusActive:
		return true
	case ConversationStatusArchived:
		return true
	default:
		return false
	}
}

// Defines values for CurrentUserLocale.
const (
	CurrentUserLocaleEn CurrentUserLocale = "en"
	CurrentUserLocaleEs CurrentUserLocale = "es"
)

// Valid indicates whether the value is a known member of the CurrentUserLocale enum.
func (e CurrentUserLocale) Valid() bool {
	switch e {
	case CurrentUserLocaleEn:
		return true
	case CurrentUserLocaleEs:
		return true
	default:
		return false
	}
}

// Defines values for CurrentUserPlan.
const (
	Free CurrentUserPlan = "free"
	Pro  CurrentUserPlan = "pro"
)

// Valid indicates whether the value is a known member of the CurrentUserPlan enum.
func (e CurrentUserPlan) Valid() bool {
	switch e {
	case Free:
		return true
	case Pro:
		return true
	default:
		return false
	}
}

// Defines values for DeletionJobStatus.
const (
	DeletionJobStatusCompleted  DeletionJobStatus = "completed"
	DeletionJobStatusFailed     DeletionJobStatus = "failed"
	DeletionJobStatusPending    DeletionJobStatus = "pending"
	DeletionJobStatusProcessing DeletionJobStatus = "processing"
)

// Valid indicates whether the value is a known member of the DeletionJobStatus enum.
func (e DeletionJobStatus) Valid() bool {
	switch e {
	case DeletionJobStatusCompleted:
		return true
	case DeletionJobStatusFailed:
		return true
	case DeletionJobStatusPending:
		return true
	case DeletionJobStatusProcessing:
		return true
	default:
		return false
	}
}

// Defines values for ErrorEnvelopeErrorCode.
const (
	ErrorEnvelopeErrorCodeConcurrencyExceeded   ErrorEnvelopeErrorCode = "concurrency_exceeded"
	ErrorEnvelopeErrorCodeConflict              ErrorEnvelopeErrorCode = "conflict"
	ErrorEnvelopeErrorCodeDependencyUnavailable ErrorEnvelopeErrorCode = "dependency_unavailable"
	ErrorEnvelopeErrorCodeForbidden             ErrorEnvelopeErrorCode = "forbidden"
	ErrorEnvelopeErrorCodeGlobalBudgetExceeded  ErrorEnvelopeErrorCode = "global_budget_exceeded"
	ErrorEnvelopeErrorCodeInvalidRequest        ErrorEnvelopeErrorCode = "invalid_request"
	ErrorEnvelopeErrorCodeMaintenance           ErrorEnvelopeErrorCode = "maintenance"
	ErrorEnvelopeErrorCodeNotFound              ErrorEnvelopeErrorCode = "not_found"
	ErrorEnvelopeErrorCodeQuotaExceeded         ErrorEnvelopeErrorCode = "quota_exceeded"
	ErrorEnvelopeErrorCodeRecentAuthRequired    ErrorEnvelopeErrorCode = "recent_auth_required"
	ErrorEnvelopeErrorCodeRefreshTokenReused    ErrorEnvelopeErrorCode = "refresh_token_reused"
	ErrorEnvelopeErrorCodeUnauthenticated       ErrorEnvelopeErrorCode = "unauthenticated"
)

// Valid indicates whether the value is a known member of the ErrorEnvelopeErrorCode enum.
func (e ErrorEnvelopeErrorCode) Valid() bool {
	switch e {
	case ErrorEnvelopeErrorCodeConcurrencyExceeded:
		return true
	case ErrorEnvelopeErrorCodeConflict:
		return true
	case ErrorEnvelopeErrorCodeDependencyUnavailable:
		return true
	case ErrorEnvelopeErrorCodeForbidden:
		return true
	case ErrorEnvelopeErrorCodeGlobalBudgetExceeded:
		return true
	case ErrorEnvelopeErrorCodeInvalidRequest:
		return true
	case ErrorEnvelopeErrorCodeMaintenance:
		return true
	case ErrorEnvelopeErrorCodeNotFound:
		return true
	case ErrorEnvelopeErrorCodeQuotaExceeded:
		return true
	case ErrorEnvelopeErrorCodeRecentAuthRequired:
		return true
	case ErrorEnvelopeErrorCodeRefreshTokenReused:
		return true
	case ErrorEnvelopeErrorCodeUnauthenticated:
		return true
	default:
		return false
	}
}

// Defines values for GenerationStatus.
const (
	GenerationStatusAccepted  GenerationStatus = "accepted"
	GenerationStatusCancelled GenerationStatus = "cancelled"
	GenerationStatusCompleted GenerationStatus = "completed"
	GenerationStatusFailed    GenerationStatus = "failed"
	GenerationStatusRejected  GenerationStatus = "rejected"
	GenerationStatusStreaming GenerationStatus = "streaming"
)

// Valid indicates whether the value is a known member of the GenerationStatus enum.
func (e GenerationStatus) Valid() bool {
	switch e {
	case GenerationStatusAccepted:
		return true
	case GenerationStatusCancelled:
		return true
	case GenerationStatusCompleted:
		return true
	case GenerationStatusFailed:
		return true
	case GenerationStatusRejected:
		return true
	case GenerationStatusStreaming:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for JobStatus.
const (
	JobStatusCompleted  JobStatus = "completed"
	JobStatusFailed     JobStatus = "failed"
	JobStatusPending    JobStatus = "pending"
	JobStatusProcessing JobStatus = "processing"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case JobStatusCompleted:
		return true
	case JobStatusFailed:
		return true
	case JobStatusPending:
		return true
	case JobStatusProcessing:
		return true
	default:
		return false
	}
}

// Defines values for MessageRole.
const (
	MessageRoleAssistant MessageRole = "assistant"
	MessageRoleUser      MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case MessageRoleAssistant:
		return true
	case MessageRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for MessageStatus.
const (
	MessageStatusCancelled MessageStatus = "cancelled"
	MessageStatusComplete  MessageStatus = "complete"
	MessageStatusFailed    MessageStatus = "failed"
	MessageStatusPending   MessageStatus = "pending"
)

// Valid indicates whether the value is a known member of the MessageStatus enum.
func (e MessageStatus) Valid() bool {
	switch e {
	case MessageStatusCancelled:
		return true
	case MessageStatusComplete:
		return true
	case MessageStatusFailed:
		return true
	case MessageStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for ModelCapabilitiesChatCompletions.
const (
	ModelCapabilitiesChatCompletionsTrue ModelCapabilitiesChatCompletions = true
)

// Valid indicates whether the value is a known member of the ModelCapabilitiesChatCompletions enum.
func (e ModelCapabilitiesChatCompletions) Valid() bool {
	switch e {
	case ModelCapabilitiesChatCompletionsTrue:
		return true
	default:
		return false
	}
}

// Defines values for PublicConfigGuestPolicyResetsAutomatically.
const (
	False PublicConfigGuestPolicyResetsAutomatically = false
)

// Valid indicates whether the value is a known member of the PublicConfigGuestPolicyResetsAutomatically enum.
func (e PublicConfigGuestPolicyResetsAutomatically) Valid() bool {
	switch e {
	case False:
		return true
	default:
		return false
	}
}

// Defines values for PublicConfigLegalMinimumAge.
const (
	N18 PublicConfigLegalMinimumAge = 18
)

// Valid indicates whether the value is a known member of the PublicConfigLegalMinimumAge enum.
func (e PublicConfigLegalMinimumAge) Valid() bool {
	switch e {
	case N18:
		return true
	default:
		return false
	}
}

// Defines values for PublicConfigLocales.
const (
	PublicConfigLocalesEn PublicConfigLocales = "en"
	PublicConfigLocalesEs PublicConfigLocales = "es"
)

// Valid indicates whether the value is a known member of the PublicConfigLocales enum.
func (e PublicConfigLocales) Valid() bool {
	switch e {
	case PublicConfigLocalesEn:
		return true
	case PublicConfigLocalesEs:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessDependencies.
const (
	Degraded ReadinessDependencies = "degraded"
	Down     ReadinessDependencies = "down"
	Up       ReadinessDependencies = "up"
)

// Valid indicates whether the value is a known member of the ReadinessDependencies enum.
func (e ReadinessDependencies) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Down:
		return true
	case Up:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessStatus.
const (
	NotReady ReadinessStatus = "not_ready"
	Ready    ReadinessStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadinessStatus enum.
func (e ReadinessStatus) Valid() bool {
	switch e {
	case NotReady:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	RoleAdmin Role = "admin"
	RoleUser  Role = "user"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case RoleAdmin:
		return true
	case RoleUser:
		return true
	default:
		return false
	}
}

// Defines values for UpdateAdminModelAudience.
const (
	UpdateAdminModelAudienceGuest UpdateAdminModelAudience = "guest"
	UpdateAdminModelAudienceUser  UpdateAdminModelAudience = "user"
)

// Valid indicates whether the value is a known member of the UpdateAdminModelAudience enum.
func (e UpdateAdminModelAudience) Valid() bool {
	switch e {
	case UpdateAdminModelAudienceGuest:
		return true
	case UpdateAdminModelAudienceUser:
		return true
	default:
		return false
	}
}

// Defines values for UpdateAdminModelDefaultFor.
const (
	UpdateAdminModelDefaultForGuest UpdateAdminModelDefaultFor = "guest"
	UpdateAdminModelDefaultForUser  UpdateAdminModelDefaultFor = "user"
)

// Valid indicates whether the value is a known member of the UpdateAdminModelDefaultFor enum.
func (e UpdateAdminModelDefaultFor) Valid() bool {
	switch e {
	case UpdateAdminModelDefaultForGuest:
		return true
	case UpdateAdminModelDefaultForUser:
		return true
	default:
		return false
	}
}

// Defines values for StartGoogleLoginParamsTermsAccepted.
const (
	StartGoogleLoginParamsTermsAcceptedTrue StartGoogleLoginParamsTermsAccepted = true
)

// Valid indicates whether the value is a known member of the StartGoogleLoginParamsTermsAccepted enum.
func (e StartGoogleLoginParamsTermsAccepted) Valid() bool {
	switch e {
	case StartGoogleLoginParamsTermsAcceptedTrue:
		return true
	default:
		return false
	}
}

// Defines values for StartGoogleLoginParamsPrivacyAccepted.
const (
	StartGoogleLoginParamsPrivacyAcceptedTrue StartGoogleLoginParamsPrivacyAccepted = true
)

// Valid indicates whether the value is a known member of the StartGoogleLoginParamsPrivacyAccepted enum.
func (e StartGoogleLoginParamsPrivacyAccepted) Valid() bool {
	switch e {
	case StartGoogleLoginParamsPrivacyAcceptedTrue:
		return true
	default:
		return false
	}
}

// Defines values for RequestAccountDeletionJSONBodyConfirmation.
const (
	DELETE RequestAccountDeletionJSONBodyConfirmation = "DELETE"
)

// Valid indicates whether the value is a known member of the RequestAccountDeletionJSONBodyConfirmation enum.
func (e RequestAccountDeletionJSONBodyConfirmation) Valid() bool {
	switch e {
	case DELETE:
		return true
	default:
		return false
	}
}

// Defines values for UpdateCurrentUserJSONBodyLocale.
const (
	UpdateCurrentUserJSONBodyLocaleEn UpdateCurrentUserJSONBodyLocale = "en"
	UpdateCurrentUserJSONBodyLocaleEs UpdateCurrentUserJSONBodyLocale = "es"
)

// Valid indicates whether the value is a known member of the UpdateCurrentUserJSONBodyLocale enum.
func (e UpdateCurrentUserJSONBodyLocale) Valid() bool {
	switch e {
	case UpdateCurrentUserJSONBodyLocaleEn:
		return true
	case UpdateCurrentUserJSONBodyLocaleEs:
		return true
	default:
		return false
	}
}

// AdminModel defines model for AdminModel.
type AdminModel struct {
	Audience     []AdminModelAudience `json:"audience"`
	Available    bool                 `json:"available"`
	Capabilities struct {
		ChatCompletions AdminModelCapabilitiesChatCompletions `json:"chatCompletions"`
		Code            bool                                  `json:"code"`
		Markdown        bool                                  `json:"markdown"`
	} `json:"capabilities"`
	DefaultFor  []AdminModelDefaultFor `json:"defaultFor"`
	Description *string                `json:"description,omitempty"`
	Enabled     bool                   `json:"enabled"`
	Id          Id                     `json:"id"`
	Name        string                 `json:"name"`
	Order       int                    `json:"order"`
	Supported   bool                   `json:"supported"`
	Version     int                    `json:"version"`
}

// AdminModelAudience defines model for AdminModel.Audience.
type AdminModelAudience string

// AdminModelCapabilitiesChatCompletions defines model for AdminModel.Capabilities.ChatCompletions.
type AdminModelCapabilitiesChatCompletions bool

// AdminModelDefaultFor defines model for AdminModel.DefaultFor.
type AdminModelDefaultFor string

// AdminUsage defines model for AdminUsage.
type AdminUsage struct {
	Currency      *string   `json:"currency,omitempty"`
	EstimatedCost float32   `json:"estimatedCost"`
	Generations   int       `json:"generations"`
	InputTokens   int       `json:"inputTokens"`
	OutputTokens  int       `json:"outputTokens"`
	PeriodEnd     time.Time `json:"periodEnd"`
	PeriodStart   time.Time `json:"periodStart"`
}

// AdminUser defines model for AdminUser.
type AdminUser struct {
	CreatedAt   time.Time           `json:"createdAt"`
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Id          Id                  `json:"id"`
	Role        Role                `json:"role"`
	Status      AdminUserStatus     `json:"status"`
	Version     int                 `json:"version"`
}

// AdminUserStatus defines model for AdminUser.Status.
type AdminUserStatus string

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action     string                  `json:"action"`
	ActorId    Id                      `json:"actorId"`
	After      *map[string]interface{} `json:"after,omitempty"`
	Before     *map[string]interface{} `json:"before,omitempty"`
	Id         Id                      `json:"id"`
	OccurredAt time.Time               `json:"occurredAt"`
	TargetId   string                  `json:"targetId"`
	TargetType string                  `json:"targetType"`
}

// AuthSession defines model for AuthSession.
type AuthSession struct {
	CreatedAt   time.Time `json:"createdAt"`
	Current     bool      `json:"current"`
	DeviceLabel *string   `json:"deviceLabel,omitempty"`
	ExpiresAt   time.Time `json:"expiresAt"`
	Id          Id        `json:"id"`
	LastSeenAt  time.Time `json:"lastSeenAt"`
}

// Conversation defines model for Conversation.
type Conversation struct {
	CreatedAt       time.Time                   `json:"createdAt"`
	GenerationState ConversationGenerationState `json:"generationState"`
	Id              Id                          `json:"id"`
	ModelId         Id                          `json:"modelId"`
	Status          ConversationStatus          `json:"status"`
	Title           string                      `json:"title"`
	UpdatedAt       time.Time                   `json:"updatedAt"`
}

// ConversationGenerationState defines model for Conversation.GenerationState.
type ConversationGenerationState string

// ConversationStatus defines model for Conversation.Status.
type ConversationStatus string

// ConversationPage defines model for ConversationPage.
type ConversationPage struct {
	Items      []Conversation `json:"items"`
	NextCursor *string        `json:"nextCursor,omitempty"`
}

// CreateConversation defines model for CreateConversation.
type CreateConversation struct {
	ModelId *Id     `json:"modelId,omitempty"`
	Title   *string `json:"title,omitempty"`
}

// CurrentUser defines model for CurrentUser.
type CurrentUser struct {
	AvatarUrl   *string             `json:"avatarUrl,omitempty"`
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Id          Id                  `json:"id"`
	Locale      CurrentUserLocale   `json:"locale"`
	Permissions []string            `json:"permissions"`
	Plan        CurrentUserPlan     `json:"plan"`
	Role        Role                `json:"role"`
}

// CurrentUserLocale defines model for CurrentUser.Locale.
type CurrentUserLocale string

// CurrentUserPlan defines model for CurrentUser.Plan.
type CurrentUserPlan string

// DeletionJob defines model for DeletionJob.
type DeletionJob struct {
	CompletedAt *time.Time        `json:"completedAt,omitempty"`
	DueAt       time.Time         `json:"dueAt"`
	Id          Id                `json:"id"`
	RequestedAt time.Time         `json:"requestedAt"`
	Status      DeletionJobStatus `json:"status"`
}

// DeletionJobStatus defines model for DeletionJob.Status.
type DeletionJobStatus string

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error struct {
		Code      ErrorEnvelopeErrorCode  `json:"code"`
		Details   *map[string]interface{} `json:"details,omitempty"`
		Message   string                  `json:"message"`
		RequestId string                  `json:"requestId"`
	} `json:"error"`
}

// ErrorEnvelopeErrorCode defines model for ErrorEnvelope.Error.Code.
type ErrorEnvelopeErrorCode string

// Generation defines model for Generation.
type Generation struct {
	ConversationId Id               `json:"conversationId"`
	CreatedAt      time.Time        `json:"createdAt"`
	Id             Id               `json:"id"`
	Retryable      *bool            `json:"retryable,omitempty"`
	Status         GenerationStatus `json:"status"`
}

// GenerationStatus defines model for Generation.Status.
type GenerationStatus string

// GuestAllowance defines model for GuestAllowance.
type GuestAllowance struct {
	Exhausted        bool      `json:"exhausted"`
	ExpiresAt        time.Time `json:"expiresAt"`
	MessageLimit     int       `json:"messageLimit"`
	MessagesUsed     int       `json:"messagesUsed"`
	OutputTokenLimit int       `json:"outputTokenLimit"`
	OutputTokensUsed int       `json:"outputTokensUsed"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Id defines model for Id.
type Id = string

// Job defines model for Job.
type Job struct {
	Id     Id        `json:"id"`
	Status JobStatus `json:"status"`
}

// JobStatus defines model for Job.Status.
type JobStatus string

// Message defines model for Message.
type Message struct {
	Content        string        `json:"content"`
	ConversationId Id            `json:"conversationId"`
	CreatedAt      time.Time     `json:"createdAt"`
	Id             Id            `json:"id"`
	Role           MessageRole   `json:"role"`
	Sequence       int           `json:"sequence"`
	Status         MessageStatus `json:"status"`
}

// MessageRole defines model for Message.Role.
type MessageRole string

// MessageStatus defines model for Message.Status.
type MessageStatus string

// MessagePage defines model for MessagePage.
type MessagePage struct {
	Items      []Message `json:"items"`
	NextCursor *string   `json:"nextCursor,omitempty"`
}

// Model defines model for Model.
type Model struct {
	Capabilities struct {
		ChatCompletions ModelCapabilitiesChatCompletions `json:"chatCompletions"`
		Code            bool                             `json:"code"`
		Markdown        bool                             `json:"markdown"`
	} `json:"capabilities"`
	Description *string `json:"description,omitempty"`
	Id          Id      `json:"id"`
	Name        string  `json:"name"`
}

// ModelCapabilitiesChatCompletions defines model for Model.Capabilities.ChatCompletions.
type ModelCapabilitiesChatCompletions bool

// PublicConfig defines model for PublicConfig.
type PublicConfig struct {
	GuestPolicy struct {
		MessageLimit        int                                        `json:"messageLimit"`
		OutputTokenLimit    int                                        `json:"outputTokenLimit"`
		ResetsAutomatically PublicConfigGuestPolicyResetsAutomatically `json:"resetsAutomatically"`
	} `json:"guestPolicy"`
	Legal struct {
		MinimumAge     PublicConfigLegalMinimumAge `json:"minimumAge"`
		PrivacyVersion string                      `json:"privacyVersion"`
		TermsVersion   string                      `json:"termsVersion"`
	} `json:"legal"`
	Locales     []PublicConfigLocales `json:"locales"`
	Maintenance bool                  `json:"maintenance"`
}

// PublicConfigGuestPolicyResetsAutomatically defines model for PublicConfig.GuestPolicy.ResetsAutomatically.
type PublicConfigGuestPolicyResetsAutomatically bool

// PublicConfigLegalMinimumAge defines model for PublicConfig.Legal.MinimumAge.
type PublicConfigLegalMinimumAge int

// PublicConfigLocales defines model for PublicConfig.Locales.
type PublicConfigLocales string

// Readiness defines model for Readiness.
type Readiness struct {
	Dependencies map[string]ReadinessDependencies `json:"dependencies"`
	Status       ReadinessStatus                  `json:"status"`
}

// ReadinessDependencies defines model for Readiness.Dependencies.
type ReadinessDependencies string

// ReadinessStatus defines model for Readiness.Status.
type ReadinessStatus string

// Role defines model for Role.
type Role string

// RuntimeSetting defines model for RuntimeSetting.
type RuntimeSetting struct {
	Key       string      `json:"key"`
	UpdatedAt time.Time   `json:"updatedAt"`
	Value     interface{} `json:"value"`
	Version   int         `json:"version"`
}

// UpdateAdminModel defines model for UpdateAdminModel.
type UpdateAdminModel struct {
	Audience   *[]UpdateAdminModelAudience   `json:"audience,omitempty"`
	DefaultFor *[]UpdateAdminModelDefaultFor `json:"defaultFor,omitempty"`
	Enabled    *bool                         `json:"enabled,omitempty"`
	Order      *int                          `json:"order,omitempty"`
}

// UpdateAdminModelAudience defines model for UpdateAdminModel.Audience.
type UpdateAdminModelAudience string

// UpdateAdminModelDefaultFor defines model for UpdateAdminModel.DefaultFor.
type UpdateAdminModelDefaultFor string

// UpdateConversation defines model for UpdateConversation.
type UpdateConversation struct {
	Archived *bool   `json:"archived,omitempty"`
	ModelId  *Id     `json:"modelId,omitempty"`
	Title    *string `json:"title,omitempty"`
}

// Usage defines model for Usage.
type Usage struct {
	Concurrency  UsageBucket `json:"concurrency"`
	Messages     UsageBucket `json:"messages"`
	OutputTokens UsageBucket `json:"outputTokens"`
}

// UsageBucket defines model for UsageBucket.
type UsageBucket struct {
	Limit   int        `json:"limit"`
	ResetAt *time.Time `json:"resetAt,omitempty"`
	Used    int        `json:"used"`
}

// After defines model for After.
type After = string

// ConversationId defines model for ConversationId.
type ConversationId = Id

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// IfMatch defines model for IfMatch.
type IfMatch = string

// Limit defines model for Limit.
type Limit = int

// ModelId defines model for ModelId.
type ModelId = Id

// SessionId defines model for SessionId.
type SessionId = Id

// BadRequest defines model for BadRequest.
type BadRequest = ErrorEnvelope

// Conflict defines model for Conflict.
type Conflict = ErrorEnvelope

// Forbidden defines model for Forbidden.
type Forbidden = ErrorEnvelope

// NotFound defines model for NotFound.
type NotFound = ErrorEnvelope

// QuotaExceeded defines model for QuotaExceeded.
type QuotaExceeded = ErrorEnvelope

// RecentAuthRequired defines model for RecentAuthRequired.
type RecentAuthRequired = ErrorEnvelope

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorEnvelope

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorEnvelope

// AdminListAuditEventsParams defines parameters for AdminListAuditEvents.
type AdminListAuditEventsParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
	After *After `form:"after,omitempty" json:"after,omitempty"`
}

// AdminSyncModelsParams defines parameters for AdminSyncModels.
type AdminSyncModelsParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// AdminUpdateModelParams defines parameters for AdminUpdateModel.
type AdminUpdateModelParams struct {
	// IfMatch Quoted current resource version.
	IfMatch IfMatch `json:"If-Match"`
}

// AdminUpdateSettingJSONBody defines parameters for AdminUpdateSetting.
type AdminUpdateSettingJSONBody struct {
	Value interface{} `json:"value"`
}

// AdminUpdateSettingParams defines parameters for AdminUpdateSetting.
type AdminUpdateSettingParams struct {
	// IfMatch Quoted current resource version.
	IfMatch IfMatch `json:"If-Match"`
}

// AdminListUsersParams defines parameters for AdminListUsers.
type AdminListUsersParams struct {
	Limit *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	After *After  `form:"after,omitempty" json:"after,omitempty"`
	Query *string `form:"query,omitempty" json:"query,omitempty"`
}

// AdminUpdateUserRoleJSONBody defines parameters for AdminUpdateUserRole.
type AdminUpdateUserRoleJSONBody struct {
	Role Role `json:"role"`
}

// AdminUpdateUserRoleParams defines parameters for AdminUpdateUserRole.
type AdminUpdateUserRoleParams struct {
	// IfMatch Quoted current resource version.
	IfMatch IfMatch `json:"If-Match"`
}

// CompleteGoogleLoginParams defines parameters for CompleteGoogleLogin.
type CompleteGoogleLoginParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// StartGoogleLoginParams defines parameters for StartGoogleLogin.
type StartGoogleLoginParams struct {
	// ReturnTo Allowlisted relative application path.
	ReturnTo *string `form:"returnTo,omitempty" json:"returnTo,omitempty"`

	// TermsAccepted Explicit acceptance of the currently advertised terms version.
	TermsAccepted StartGoogleLoginParamsTermsAccepted `form:"termsAccepted" json:"termsAccepted"`

	// PrivacyAccepted Explicit acceptance of the currently advertised privacy version.
	PrivacyAccepted StartGoogleLoginParamsPrivacyAccepted `form:"privacyAccepted" json:"privacyAccepted"`
}

// StartGoogleLoginParamsTermsAccepted defines parameters for StartGoogleLogin.
type StartGoogleLoginParamsTermsAccepted bool

// StartGoogleLoginParamsPrivacyAccepted defines parameters for StartGoogleLogin.
type StartGoogleLoginParamsPrivacyAccepted bool

// ListConversationsParams defines parameters for ListConversations.
type ListConversationsParams struct {
	Limit    *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	After    *After  `form:"after,omitempty" json:"after,omitempty"`
	Query    *string `form:"query,omitempty" json:"query,omitempty"`
	Archived *bool   `form:"archived,omitempty" json:"archived,omitempty"`
}

// CreateConversationParams defines parameters for CreateConversation.
type CreateConversationParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// DeleteConversationParams defines parameters for DeleteConversation.
type DeleteConversationParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListMessagesParams defines parameters for ListMessages.
type ListMessagesParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
	After *After `form:"after,omitempty" json:"after,omitempty"`
}

// RetryLatestGenerationParams defines parameters for RetryLatestGeneration.
type RetryLatestGenerationParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// RequestAccountDeletionJSONBody defines parameters for RequestAccountDeletion.
type RequestAccountDeletionJSONBody struct {
	Confirmation RequestAccountDeletionJSONBodyConfirmation `json:"confirmation"`
}

// RequestAccountDeletionParams defines parameters for RequestAccountDeletion.
type RequestAccountDeletionParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// RequestAccountDeletionJSONBodyConfirmation defines parameters for RequestAccountDeletion.
type RequestAccountDeletionJSONBodyConfirmation string

// UpdateCurrentUserJSONBody defines parameters for UpdateCurrentUser.
type UpdateCurrentUserJSONBody struct {
	Locale UpdateCurrentUserJSONBodyLocale `json:"locale"`
}

// UpdateCurrentUserJSONBodyLocale defines parameters for UpdateCurrentUser.
type UpdateCurrentUserJSONBodyLocale string

// RevokeAuthSessionParams defines parameters for RevokeAuthSession.
type RevokeAuthSessionParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// AdminUpdateModelJSONRequestBody defines body for AdminUpdateModel for application/json ContentType.
type AdminUpdateModelJSONRequestBody = UpdateAdminModel

// AdminUpdateSettingJSONRequestBody defines body for AdminUpdateSetting for application/json ContentType.
type AdminUpdateSettingJSONRequestBody AdminUpdateSettingJSONBody

// AdminUpdateUserRoleJSONRequestBody defines body for AdminUpdateUserRole for application/json ContentType.
type AdminUpdateUserRoleJSONRequestBody AdminUpdateUserRoleJSONBody

// CreateConversationJSONRequestBody defines body for CreateConversation for application/json ContentType.
type CreateConversationJSONRequestBody = CreateConversation

// UpdateConversationJSONRequestBody defines body for UpdateConversation for application/json ContentType.
type UpdateConversationJSONRequestBody = UpdateConversation

// RequestAccountDeletionJSONRequestBody defines body for RequestAccountDeletion for application/json ContentType.
type RequestAccountDeletionJSONRequestBody RequestAccountDeletionJSONBody

// UpdateCurrentUserJSONRequestBody defines body for UpdateCurrentUser for application/json ContentType.
type UpdateCurrentUserJSONRequestBody UpdateCurrentUserJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// AdminListAuditEvents List administrative audit events
	// (GET /admin/audit-log)
	AdminListAuditEvents(w http.ResponseWriter, r *http.Request, params AdminListAuditEventsParams)
	// AdminListModels List models for administration
	// (GET /admin/models)
	AdminListModels(w http.ResponseWriter, r *http.Request)
	// AdminSyncModels Synchronize provider model metadata
	// (POST /admin/models/sync)
	AdminSyncModels(w http.ResponseWriter, r *http.Request, params AdminSyncModelsParams)
	// AdminUpdateModel Update model exposure
	// (PATCH /admin/models/{modelId})
	AdminUpdateModel(w http.ResponseWriter, r *http.Request, modelId ModelId, params AdminUpdateModelParams)
	// AdminListSettings List runtime settings
	// (GET /admin/settings)
	AdminListSettings(w http.ResponseWriter, r *http.Request)
	// AdminUpdateSetting Update a runtime setting
	// (PATCH /admin/settings/{key})
	AdminUpdateSetting(w http.ResponseWriter, r *http.Request, key string, params AdminUpdateSettingParams)
	// AdminGetUsage Get aggregate service usage
	// (GET /admin/usage)
	AdminGetUsage(w http.ResponseWriter, r *http.Request)
	// AdminListUsers List users for administration
	// (GET /admin/users)
	AdminListUsers(w http.ResponseWriter, r *http.Request, params AdminListUsersParams)
	// AdminUpdateUserRole Update a user role
	// (PATCH /admin/users/{userId}/role)
	AdminUpdateUserRole(w http.ResponseWriter, r *http.Request, userId Id, params AdminUpdateUserRoleParams)
	// CompleteGoogleLogin Complete Google login
	// (GET /auth/google/callback)
	CompleteGoogleLogin(w http.ResponseWriter, r *http.Request, params CompleteGoogleLoginParams)
	// StartGoogleLogin Start Google login
	// (GET /auth/google/start)
	StartGoogleLogin(w http.ResponseWriter, r *http.Request, params StartGoogleLoginParams)
	// Logout Log out the current session
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// RefreshAuthSession Rotate the refresh token
	// (POST /auth/refresh)
	RefreshAuthSession(w http.ResponseWriter, r *http.Request)
	// CreateWebSocketTicket Create a WebSocket ticket
	// (POST /auth/ws-ticket)
	CreateWebSocketTicket(w http.ResponseWriter, r *http.Request)
	// GetPublicConfig Get public runtime configuration
	// (GET /config/public)
	GetPublicConfig(w http.ResponseWriter, r *http.Request)
	// ListConversations List owned conversations
	// (GET /conversations)
	ListConversations(w http.ResponseWriter, r *http.Request, params ListConversationsParams)
	// CreateConversation Create a conversation
	// (POST /conversations)
	CreateConversation(w http.ResponseWriter, r *http.Request, params CreateConversationParams)
	// DeleteConversation Delete a conversation
	// (DELETE /conversations/{conversationId})
	DeleteConversation(w http.ResponseWriter, r *http.Request, conversationId ConversationId, params DeleteConversationParams)
	// GetConversation Get an owned conversation
	// (GET /conversations/{conversationId})
	GetConversation(w http.ResponseWriter, r *http.Request, conversationId ConversationId)
	// UpdateConversation Update a conversation
	// (PATCH /conversations/{conversationId})
	UpdateConversation(w http.ResponseWriter, r *http.Request, conversationId ConversationId)
	// ListMessages List conversation messages
	// (GET /conversations/{conversationId}/messages)
	ListMessages(w http.ResponseWriter, r *http.Request, conversationId ConversationId, params ListMessagesParams)
	// RetryLatestGeneration Retry the latest failed generation
	// (POST /conversations/{conversationId}/retry)
	RetryLatestGeneration(w http.ResponseWriter, r *http.Request, conversationId ConversationId, params RetryLatestGenerationParams)
	// CreateOrResumeGuestSession Create or resume a guest session
	// (POST /guest-sessions)
	CreateOrResumeGuestSession(w http.ResponseWriter, r *http.Request)
	// GetCurrentGuestSession Get the current guest allowance
	// (GET /guest-sessions/current)
	GetCurrentGuestSession(w http.ResponseWriter, r *http.Request)
	// GetLiveness Check process liveness
	// (GET /health/live)
	GetLiveness(w http.ResponseWriter, r *http.Request)
	// GetReadiness Check dependency readiness
	// (GET /health/ready)
	GetReadiness(w http.ResponseWriter, r *http.Request)
	// RequestAccountDeletion Request account deletion
	// (DELETE /me)
	RequestAccountDeletion(w http.ResponseWriter, r *http.Request, params RequestAccountDeletionParams)
	// GetCurrentUser Get the current user
	// (GET /me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// UpdateCurrentUser Update current-user preferences
	// (PATCH /me)
	UpdateCurrentUser(w http.ResponseWriter, r *http.Request)
	// GetAccountDeletion Get account deletion state
	// (GET /me/deletion)
	GetAccountDeletion(w http.ResponseWriter, r *http.Request)
	// StartReauthentication Start recent reauthentication
	// (POST /me/reauthenticate)
	StartReauthentication(w http.ResponseWriter, r *http.Request)
	// ListAuthSessions List device sessions
	// (GET /me/sessions)
	ListAuthSessions(w http.ResponseWriter, r *http.Request)
	// RevokeAuthSession Revoke a device session
	// (DELETE /me/sessions/{sessionId})
	RevokeAuthSession(w http.ResponseWriter, r *http.Request, sessionId SessionId, params RevokeAuthSessionParams)
	// ListVisibleModels List models visible to the actor
	// (GET /models)
	ListVisibleModels(w http.ResponseWriter, r *http.Request)
	// GetUsage Get current quota usage
	// (GET /usage)
	GetUsage(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// AdminListAuditEvents List administrative audit events
// (GET /admin/audit-log)
func (_ Unimplemented) AdminListAuditEvents(w http.ResponseWriter, r *http.Request, params AdminListAuditEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AdminListModels List models for administration
// (GET /admin/models)
func (_ Unimplemented) AdminListModels(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AdminSyncModels Synchronize provider model metadata
// (POST /admin/models/sync)
func (_ Unimplemented) AdminSyncModels(w http.ResponseWriter, r *http.Request, params AdminSyncModelsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AdminUpdateModel Update model exposure
// (PATCH /admin/models/{modelId})
func (_ Unimplemented) AdminUpdateModel(w http.ResponseWriter, r *http.Request, modelId ModelId, params AdminUpdateModelParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AdminListSettings List runtime settings
// (GET /admin/settings)
func (_ Unimplemented) AdminListSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AdminUpdateSetting Update a runtime setting
// (PATCH /admin/settings/{key})
func (_ Unimplemented) AdminUpdateSetting(w http.ResponseWriter, r *http.Request, key string, params AdminUpdateSettingParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AdminGetUsage Get aggregate service usage
// (GET /admin/usage)
func (_ Unimplemented) AdminGetUsage(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AdminListUsers List users for administration
// (GET /admin/users)
func (_ Unimplemented) AdminListUsers(w http.ResponseWriter, r *http.Request, params AdminListUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AdminUpdateUserRole Update a user role
// (PATCH /admin/users/{userId}/role)
func (_ Unimplemented) AdminUpdateUserRole(w http.ResponseWriter, r *http.Request, userId Id, params AdminUpdateUserRoleParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CompleteGoogleLogin Complete Google login
// (GET /auth/google/callback)
func (_ Unimplemented) CompleteGoogleLogin(w http.ResponseWriter, r *http.Request, params CompleteGoogleLoginParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// StartGoogleLogin Start Google login
// (GET /auth/google/start)
func (_ Unimplemented) StartGoogleLogin(w http.ResponseWriter, r *http.Request, params StartGoogleLoginParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout Log out the current session
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RefreshAuthSession Rotate the refresh token
// (POST /auth/refresh)
func (_ Unimplemented) RefreshAuthSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateWebSocketTicket Create a WebSocket ticket
// (POST /auth/ws-ticket)
func (_ Unimplemented) CreateWebSocketTicket(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetPublicConfig Get public runtime configuration
// (GET /config/public)
func (_ Unimplemented) GetPublicConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListConversations List owned conversations
// (GET /conversations)
func (_ Unimplemented) ListConversations(w http.ResponseWriter, r *http.Request, params ListConversationsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateConversation Create a conversation
// (POST /conversations)
func (_ Unimplemented) CreateConversation(w http.ResponseWriter, r *http.Request, params CreateConversationParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteConversation Delete a conversation
// (DELETE /conversations/{conversationId})
func (_ Unimplemented) DeleteConversation(w http.ResponseWriter, r *http.Request, conversationId ConversationId, params DeleteConversationParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetConversation Get an owned conversation
// (GET /conversations/{conversationId})
func (_ Unimplemented) GetConversation(w http.ResponseWriter, r *http.Request, conversationId ConversationId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateConversation Update a conversation
// (PATCH /conversations/{conversationId})
func (_ Unimplemented) UpdateConversation(w http.ResponseWriter, r *http.Request, conversationId ConversationId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListMessages List conversation messages
// (GET /conversations/{conversationId}/messages)
func (_ Unimplemented) ListMessages(w http.ResponseWriter, r *http.Request, conversationId ConversationId, params ListMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RetryLatestGeneration Retry the latest failed generation
// (POST /conversations/{conversationId}/retry)
func (_ Unimplemented) RetryLatestGeneration(w http.ResponseWriter, r *http.Request, conversationId ConversationId, params RetryLatestGenerationParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateOrResumeGuestSession Create or resume a guest session
// (POST /guest-sessions)
func (_ Unimplemented) CreateOrResumeGuestSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetCurrentGuestSession Get the current guest allowance
// (GET /guest-sessions/current)
func (_ Unimplemented) GetCurrentGuestSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetLiveness Check process liveness
// (GET /health/live)
func (_ Unimplemented) GetLiveness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetReadiness Check dependency readiness
// (GET /health/ready)
func (_ Unimplemented) GetReadiness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RequestAccountDeletion Request account deletion
// (DELETE /me)
func (_ Unimplemented) RequestAccountDeletion(w http.ResponseWriter, r *http.Request, params RequestAccountDeletionParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetCurrentUser Get the current user
// (GET /me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateCurrentUser Update current-user preferences
// (PATCH /me)
func (_ Unimplemented) UpdateCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetAccountDeletion Get account deletion state
// (GET /me/deletion)
func (_ Unimplemented) GetAccountDeletion(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// StartReauthentication Start recent reauthentication
// (POST /me/reauthenticate)
func (_ Unimplemented) StartReauthentication(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListAuthSessions List device sessions
// (GET /me/sessions)
func (_ Unimplemented) ListAuthSessions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RevokeAuthSession Revoke a device session
// (DELETE /me/sessions/{sessionId})
func (_ Unimplemented) RevokeAuthSession(w http.ResponseWriter, r *http.Request, sessionId SessionId, params RevokeAuthSessionParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListVisibleModels List models visible to the actor
// (GET /models)
func (_ Unimplemented) ListVisibleModels(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetUsage Get current quota usage
// (GET /usage)
func (_ Unimplemented) GetUsage(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AdminListAuditEvents operation middleware
func (siw *ServerInterfaceWrapper) AdminListAuditEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params AdminListAuditEventsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after", r.URL.Query(), &params.After, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminListAuditEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminListModels operation middleware
func (siw *ServerInterfaceWrapper) AdminListModels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminListModels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminSyncModels operation middleware
func (siw *ServerInterfaceWrapper) AdminSyncModels(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params AdminSyncModelsParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminSyncModels(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminUpdateModel operation middleware
func (siw *ServerInterfaceWrapper) AdminUpdateModel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "modelId" -------------
	var modelId ModelId

	err = runtime.BindStyledParameterWithOptions("simple", "modelId", chi.URLParam(r, "modelId"), &modelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "modelId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params AdminUpdateModelParams

	headers := r.Header

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminUpdateModel(w, r, modelId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminListSettings operation middleware
func (siw *ServerInterfaceWrapper) AdminListSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminListSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminUpdateSetting operation middleware
func (siw *ServerInterfaceWrapper) AdminUpdateSetting(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", chi.URLParam(r, "key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params AdminUpdateSettingParams

	headers := r.Header

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminUpdateSetting(w, r, key, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminGetUsage operation middleware
func (siw *ServerInterfaceWrapper) AdminGetUsage(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminGetUsage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminListUsers operation middleware
func (siw *ServerInterfaceWrapper) AdminListUsers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params AdminListUsersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after", r.URL.Query(), &params.After, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "query", r.URL.Query(), &params.Query, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "query"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminListUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminUpdateUserRole operation middleware
func (siw *ServerInterfaceWrapper) AdminUpdateUserRole(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId Id

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params AdminUpdateUserRoleParams

	headers := r.Header

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch IfMatch
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminUpdateUserRole(w, r, userId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteGoogleLogin operation middleware
func (siw *ServerInterfaceWrapper) CompleteGoogleLogin(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CompleteGoogleLoginParams

	// ------------- Required query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	// ------------- Required query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteGoogleLogin(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartGoogleLogin operation middleware
func (siw *ServerInterfaceWrapper) StartGoogleLogin(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params StartGoogleLoginParams

	// ------------- Optional query parameter "returnTo" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "returnTo", r.URL.Query(), &params.ReturnTo, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "returnTo"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "returnTo", Err: err})
		}
		return
	}

	// ------------- Required query parameter "termsAccepted" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "termsAccepted", r.URL.Query(), &params.TermsAccepted, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "termsAccepted"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "termsAccepted", Err: err})
		}
		return
	}

	// ------------- Required query parameter "privacyAccepted" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "privacyAccepted", r.URL.Query(), &params.PrivacyAccepted, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "privacyAccepted"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "privacyAccepted", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartGoogleLogin(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshAuthSession operation middleware
func (siw *ServerInterfaceWrapper) RefreshAuthSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshAuthSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWebSocketTicket operation middleware
func (siw *ServerInterfaceWrapper) CreateWebSocketTicket(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWebSocketTicket(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPublicConfig operation middleware
func (siw *ServerInterfaceWrapper) GetPublicConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPublicConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListConversations operation middleware
func (siw *ServerInterfaceWrapper) ListConversations(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListConversationsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after", r.URL.Query(), &params.After, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "query", r.URL.Query(), &params.Query, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "query"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "archived" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "archived", r.URL.Query(), &params.Archived, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "archived"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "archived", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListConversations(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateConversation operation middleware
func (siw *ServerInterfaceWrapper) CreateConversation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateConversationParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateConversation(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteConversation operation middleware
func (siw *ServerInterfaceWrapper) DeleteConversation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "conversationId" -------------
	var conversationId ConversationId

	err = runtime.BindStyledParameterWithOptions("simple", "conversationId", chi.URLParam(r, "conversationId"), &conversationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "conversationId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteConversationParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteConversation(w, r, conversationId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConversation operation middleware
func (siw *ServerInterfaceWrapper) GetConversation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "conversationId" -------------
	var conversationId ConversationId

	err = runtime.BindStyledParameterWithOptions("simple", "conversationId", chi.URLParam(r, "conversationId"), &conversationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "conversationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConversation(w, r, conversationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateConversation operation middleware
func (siw *ServerInterfaceWrapper) UpdateConversation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "conversationId" -------------
	var conversationId ConversationId

	err = runtime.BindStyledParameterWithOptions("simple", "conversationId", chi.URLParam(r, "conversationId"), &conversationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "conversationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateConversation(w, r, conversationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMessages operation middleware
func (siw *ServerInterfaceWrapper) ListMessages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "conversationId" -------------
	var conversationId ConversationId

	err = runtime.BindStyledParameterWithOptions("simple", "conversationId", chi.URLParam(r, "conversationId"), &conversationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "conversationId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMessagesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after", r.URL.Query(), &params.After, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMessages(w, r, conversationId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RetryLatestGeneration operation middleware
func (siw *ServerInterfaceWrapper) RetryLatestGeneration(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "conversationId" -------------
	var conversationId ConversationId

	err = runtime.BindStyledParameterWithOptions("simple", "conversationId", chi.URLParam(r, "conversationId"), &conversationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "conversationId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RetryLatestGenerationParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RetryLatestGeneration(w, r, conversationId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrResumeGuestSession operation middleware
func (siw *ServerInterfaceWrapper) CreateOrResumeGuestSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrResumeGuestSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentGuestSession operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentGuestSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentGuestSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestAccountDeletion operation middleware
func (siw *ServerInterfaceWrapper) RequestAccountDeletion(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params RequestAccountDeletionParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestAccountDeletion(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateCurrentUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccountDeletion operation middleware
func (siw *ServerInterfaceWrapper) GetAccountDeletion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccountDeletion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartReauthentication operation middleware
func (siw *ServerInterfaceWrapper) StartReauthentication(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartReauthentication(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAuthSessions operation middleware
func (siw *ServerInterfaceWrapper) ListAuthSessions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAuthSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeAuthSession operation middleware
func (siw *ServerInterfaceWrapper) RevokeAuthSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", chi.URLParam(r, "sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RevokeAuthSessionParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeAuthSession(w, r, sessionId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVisibleModels operation middleware
func (siw *ServerInterfaceWrapper) ListVisibleModels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVisibleModels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsage operation middleware
func (siw *ServerInterfaceWrapper) GetUsage(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health/live", wrapper.GetLiveness)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health/ready", wrapper.GetReadiness)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/config/public", wrapper.GetPublicConfig)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/models", wrapper.ListVisibleModels)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/guest-sessions", wrapper.CreateOrResumeGuestSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/guest-sessions/current", wrapper.GetCurrentGuestSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/google/start", wrapper.StartGoogleLogin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/google/callback", wrapper.CompleteGoogleLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.RefreshAuthSession)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/ws-ticket", wrapper.CreateWebSocketTicket)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/me", wrapper.RequestAccountDeletion)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/me", wrapper.UpdateCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/sessions", wrapper.ListAuthSessions)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/me/sessions/{sessionId}", wrapper.RevokeAuthSession)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/me/reauthenticate", wrapper.StartReauthentication)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/deletion", wrapper.GetAccountDeletion)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/conversations", wrapper.ListConversations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/conversations", wrapper.CreateConversation)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/conversations/{conversationId}", wrapper.DeleteConversation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/conversations/{conversationId}", wrapper.GetConversation)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/conversations/{conversationId}", wrapper.UpdateConversation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/conversations/{conversationId}/messages", wrapper.ListMessages)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/conversations/{conversationId}/retry", wrapper.RetryLatestGeneration)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/usage", wrapper.GetUsage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/models", wrapper.AdminListModels)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/models/sync", wrapper.AdminSyncModels)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/admin/models/{modelId}", wrapper.AdminUpdateModel)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/settings", wrapper.AdminListSettings)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/admin/settings/{key}", wrapper.AdminUpdateSetting)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/users", wrapper.AdminListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/admin/users/{userId}/role", wrapper.AdminUpdateUserRole)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/usage", wrapper.AdminGetUsage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/audit-log", wrapper.AdminListAuditEvents)
	})

	return r
}
